var Vips = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var m=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,t=ba&&self.name?.startsWith("em-pthread");m.dynamicLibraries=m.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];m.workaroundCors&&(m.mainScriptUrlOrBlob=m.mainScriptUrlOrBlob||URL.createObjectURL(new Blob([`importScripts('${_scriptName}');`],{type:"application/javascript"})));var ca=[],da="./this.program";ba&&(_scriptName=self.location.href);var ea="";
function ha(a){return m.locateFile?m.locateFile(a,ea):ea+a}var ia,ka;if(aa||ba){try{ea=(new URL(".",_scriptName)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ia=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var la=console.log.bind(console),v=console.error.bind(console),ma=[],na,oa,pa=!1,qa;class w extends Error{}
class ra extends w{}class sa extends w{constructor(a){super(a);this.va=a;a=ta(a);this.name=a[0];this.message=a[1]}}var ua,va,wa,xa={};
if(t){var ya=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.U;if("load"===d){let e=[];self.onmessage=f=>e.push(f);self.startWorker=()=>{postMessage({U:"loaded"});for(let f of e)a(f);self.onmessage=a};ma=c.zb;xa=c.kc;for(const f of c.Kb)if(!m[f]||m[f].proxy)m[f]=(...g)=>{postMessage({U:"callHandler",Jb:f,tb:g})},"print"==f&&(la=m[f]),"printErr"==f&&(v=m[f]);za=c.rc;Ba();wa(c.sc)}else if("run"===d){Ca(c.X);Da(c.X,0,0,1,0,0);Ea();Fa(c.X);ya||(Ga(),ya=!0);try{Ha(c.nc,
c.Da)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?ya&&Ia():d&&(v(`worker: received unknown command ${d}`),v(c)))}catch(e){throw Ja(),e;}}self.onmessage=a}var za,y,z,A,C,D,E,Ka,La,F,Ma,Oa=!1,Pa=!1;function Ba(){var a=za.buffer;y=new Int8Array(a);A=new Int16Array(a);z=new Uint8Array(a);C=new Uint16Array(a);D=new Int32Array(a);E=new Uint32Array(a);Ka=new Float32Array(a);La=new Float64Array(a);F=new BigInt64Array(a);Ma=new BigUint64Array(a)}var Qa=[];
function Ra(){Oa=!0;t?startWorker(m):(Sa(Qa),m.noFSInit||FS.Ga||FS.init(),Ta.__wasm_call_ctors(),Sa(Ua),FS.bb=!1)}var Va=0,Wa=null;function Xa(){Va++;m.monitorRunDependencies?.(Va)}function Ya(){Va--;m.monitorRunDependencies?.(Va);if(0==Va&&Wa){var a=Wa;Wa=null;a()}}function Za(a){m.onAbort?.(a);a="Aborted("+a+")";v(a);pa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");va?.(a);throw a;}var $a;
async function ab(a){if(!na)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==$a&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function bb(a,b){try{var c=await ab(a);return await WebAssembly.instantiate(c,b)}catch(d){v(`failed to asynchronously prepare wasm: ${d}`),Za(d)}}
async function cb(a){var b=$a;if(!na&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){v(`wasm streaming compile failed: ${d}`),v("falling back to ArrayBuffer instantiation")}return bb(b,a)}
function db(){G={__assert_fail:eb,__call_sighandler:fb,__cxa_begin_catch:gb,__cxa_end_catch:hb,__cxa_find_matching_catch_2:ib,__cxa_find_matching_catch_3:jb,__cxa_rethrow:kb,__cxa_throw:lb,__cxa_uncaught_exceptions:mb,__heap_base:nb,__indirect_function_table:ob,__lsan_ignore_object:pb,__memory_base:qb,__pthread_create_js:rb,__resumeException:sb,__stack_high:tb,__stack_low:ub,__stack_pointer:vb,__syscall_dup:wb,__syscall_faccessat:xb,__syscall_fcntl64:yb,__syscall_fstat64:zb,__syscall_ftruncate64:Ab,
__syscall_getcwd:Bb,__syscall_ioctl:Cb,__syscall_lstat64:Db,__syscall_newfstatat:Eb,__syscall_openat:Fb,__syscall_poll:Gb,__syscall_rmdir:Hb,__syscall_stat64:Ib,__syscall_unlinkat:Jb,__table_base:Kb,_abort_js:Lb,_dlopen_js:Mb,_dlsym_catchup_js:Nb,_dlsym_js:Ob,_embind_finalize_value_object:Pb,_embind_register_arithmetic_vector:Qb,_embind_register_bigint:Rb,_embind_register_bool:Sb,_embind_register_class:Tb,_embind_register_class_class_function:Ub,_embind_register_class_constructor:Vb,_embind_register_class_function:Wb,
_embind_register_class_property:Xb,_embind_register_emval:Yb,_embind_register_enum:Zb,_embind_register_enum_value:$b,_embind_register_float:ac,_embind_register_function:bc,_embind_register_integer:cc,_embind_register_memory_view:dc,_embind_register_std_string:ec,_embind_register_std_wstring:fc,_embind_register_value_object:gc,_embind_register_value_object_field:hc,_embind_register_void:ic,_emscripten_dlopen_js:jc,_emscripten_dlsync_threads:kc,_emscripten_dlsync_threads_async:lc,_emscripten_get_dynamic_libraries_js:mc,
_emscripten_init_main_thread_js:nc,_emscripten_notify_mailbox_postmessage:oc,_emscripten_receive_on_main_thread_js:pc,_emscripten_runtime_keepalive_clear:qc,_emscripten_thread_cleanup:rc,_emscripten_thread_exit_joinable:sc,_emscripten_thread_mailbox_await:Fa,_emscripten_thread_set_strongref:tc,_emscripten_throw_longjmp:uc,_emval_as:vc,_emval_call:wc,_emval_decref:xc,_emval_get_global:yc,_emval_get_method_caller:zc,_emval_get_module_property:Ac,_emval_get_property:Bc,_emval_incref:Cc,_emval_instanceof:Dc,
_emval_is_number:Ec,_emval_is_string:Fc,_emval_new_cstring:Gc,_emval_run_destructors:Hc,_emval_set_property:Ic,_emval_take_value:Jc,_emval_typeof:Kc,_gmtime_js:Lc,_localtime_js:Mc,_mmap_js:Nc,_munmap_js:Oc,_tzset_js:Pc,clock_time_get:Qc,emscripten_check_blocking_allowed:Rc,emscripten_date_now:Sc,emscripten_err:Tc,emscripten_exit_with_live_runtime:Uc,emscripten_get_heap_max:Vc,emscripten_get_now:Wc,emscripten_num_logical_cores:Xc,emscripten_promise_destroy:Yc,emscripten_promise_resolve:Zc,emscripten_resize_heap:$c,
environ_get:ad,environ_sizes_get:bd,exit:cd,fd_close:dd,fd_fdstat_get:ed,fd_read:fd,fd_seek:gd,fd_write:hd,ffi_call_js:jd,heif_color_conversion_options_ext_copy:kd,heif_color_conversion_options_ext_free:ld,heif_encoding_options_alloc:md,heif_encoding_options_free:nd,heif_error_success:od,heif_image_get_bits_per_pixel_range:pd,heif_image_get_chroma_format:qd,heif_image_get_nclx_color_profile:rd,heif_image_get_plane_readonly2:sd,heif_image_release:td,heif_nclx_color_profile_free:ud,heif_tai_clock_info_release:vd,
heif_tai_timestamp_packet_alloc:wd,heif_tai_timestamp_packet_copy:xd,heif_tai_timestamp_packet_release:yd,invoke_di:zd,invoke_dii:Ad,invoke_diii:Bd,invoke_diiii:Cd,invoke_fiii:Dd,invoke_i:Ed,invoke_ii:Fd,invoke_iii:Gd,invoke_iiid:Hd,invoke_iiii:Id,invoke_iiiii:Jd,invoke_iiiiid:Kd,invoke_iiiiii:Ld,invoke_iiiiiii:Md,invoke_iiiiiiii:Nd,invoke_iiiiiiiiiii:Od,invoke_iiiiiiiiiiii:Pd,invoke_iiiiiiiiiiiii:Qd,invoke_iiiiij:Rd,invoke_ji:Sd,invoke_jiiii:Td,invoke_v:Ud,invoke_vi:Vd,invoke_vid:Wd,invoke_viddi:Xd,
invoke_vii:Yd,invoke_viid:Zd,invoke_viidd:$d,invoke_viiddi:ae,invoke_viidi:be,invoke_viii:ce,invoke_viiid:de,invoke_viiidddddi:ee,invoke_viiiddddi:fe,invoke_viiidddi:ge,invoke_viiiddi:he,invoke_viiidi:ie,invoke_viiii:je,invoke_viiiii:ke,invoke_viiiiii:le,invoke_viiiiiii:me,invoke_viiiiiiii:ne,invoke_viiiiiiiii:oe,invoke_viiiiiiiiii:pe,invoke_viiiiiiiiiii:qe,invoke_viiiiiiiiiiii:re,invoke_viiiiiiiiiiiii:se,invoke_viiiiiiiiiiiiiii:te,memory:za,proc_exit:ue,random_get:ve};return{env:G,wasi_snapshot_preview1:G,
"GOT.mem":new Proxy(G,we),"GOT.func":new Proxy(G,we)}}var ye=a=>{if(!(a instanceof xe||"unwind"==a))throw a;};class xe{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var I=0,ze=a=>{a.terminate();a.onmessage=()=>{}},Ge=a=>{var b=Ae[a];Be.delete(a);a in Ce&&Ce[a].resolve();a=b.X;delete Ae[a];De.push(b);Ee.splice(Ee.indexOf(b),1);b.X=0;Fe(a)},Sa=a=>{for(;0<a.length;)a.shift()(m)},He=[],Ke=a=>{0==De.length&&(Ie(),Je(De[0]));var b=De.pop();if(!b)return 6;Ee.push(b);Ae[a.X]=b;b.X=a.X;b.postMessage({U:"run",nc:a.mc,Da:a.Da,X:a.X},a.nb);return 0},De=[],Ee=[],Le=[],Ae={};
function Me(){for(var a=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;a--;)Ie();He.push(()=>{Xa("loading-workers");Ne(()=>Ya("loading-workers"))});Ce={};Be=new Set}var Oe=()=>{for(var a of Ee)ze(a);for(a of De)ze(a);De=[];Ee=[];Ae={}};function Ea(){Le.forEach(a=>a())}
var Je=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.U;if(f.Ca&&f.Ca!=Pe()){var h=Ae[f.Ca];h?h.postMessage(f,f.nb):v(`Internal error! Worker sent a message "${g}" to target pthread ${f.Ca}, but that thread no longer exists!`)}else if("checkMailbox"===g)Ia();else if("spawnThread"===g)Ke(f);else if("cleanupThread"===g)Ge(f.Qa);else if("markAsFinished"===g)f=f.Qa,Be.add(f),f in Ce&&Ce[f].resolve();else if("loaded"===g)a.loaded=!0,b(a);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===
g)m[f.Jb](...f.tb);else g&&v(`worker sent an unknown command ${g}`)};a.onerror=f=>{v(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)m.propertyIsEnumerable(e)&&c.push(e);a.postMessage({U:"load",Kb:c,rc:za,sc:oa,zb:ma,kc:xa})});function Ne(a){t?a():Promise.all(De.map(Je)).then(a)}
function Ie(){var a=_scriptName;m.mainScriptUrlOrBlob&&(a=m.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{name:"em-pthread"});De.push(a)}var Be,Ce,O=(a,b,...c)=>{for(var d=2*c.length,e=J(),f=Qe(8*d),g=f>>3,h=0;h<c.length;h++){var k=c[h];"bigint"==typeof k?(F[g+2*h]=1n,F[g+2*h+1]=k):(F[g+2*h]=0n,La[g+2*h+1]=k)}a=Re(a,0,d,f,b);K(e);return a};function ue(a){if(t)return O(0,1,a);qa=a;Se||0<I||(Oe(),m.onExit?.(a),pa=!0);throw new xe(a);}ue.g="vi";
function Te(a){if(t)return O(1,0,a);cd(a)}var cd=a=>{qa=a;if(t)throw Te(a),"unwind";if(!(Se||0<I||t)){Ue();FS.Ga=!1;Ve(0);for(var b of FS.streams)b&&FS.close(b);Oe();Pa=!0}ue(a)};cd.g="vi";var Xe=a=>{if(!Pa&&!pa)try{if(a(),!(Pa||Se||0<I))try{t?We(qa):cd(qa)}catch(b){ye(b)}}catch(b){ye(b)}},Ye=a=>{I+=1;setTimeout(()=>{--I;Xe(a)},1E4)},Ze=[],$e={},af=!1;
function bf(){function a(){var c=m.canvas;af=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!cf){cf=!0;Ze.push({canHandle:function(c){return!m.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:df(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:df(d)}));var h=URL.createObjectURL(g),k=new Image;k.onload=()=>{var l=document.createElement("canvas");
l.width=k.width;l.height=k.height;l.getContext("2d").drawImage(k,0,0);URL.revokeObjectURL(h);e?.(c)};k.onerror=()=>{v(`Image ${h} could not be decoded`);f?.()};k.src=h}});Ze.push({canHandle:function(c){return!m.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,h=URL.createObjectURL(new Blob([c],{type:df(d)})),k=new Audio;k.addEventListener("canplaythrough",()=>f(k),!1);k.onerror=function(){if(!g){v(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var l="",p=0,n=0,q=0;q<c.length;q++)for(p=p<<8|c[q],n+=8;6<=n;){var r=p>>n-6&63;n-=6;l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[r]}2==n?(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(p&3)<<4],l+="=="):4==n&&(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(p&15)<<2],l+="=");k.src="data:audio/x-"+d.slice(-3)+";base64,"+l;f(k)}};k.src=h;Ye(()=>{f(k)})}});var b=m.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),m.elementPointerLock&&b.addEventListener("click",
c=>{!af&&m.canvas.requestPointerLock&&(m.canvas.requestPointerLock(),c.preventDefault())},!1))}}function df(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var ef={},cf,ff={},gf=new Set(["__lsan_ignore_object","__lsan_ignore_object"]),we={get(a,b){(a=ff[b])||(a=ff[b]=new WebAssembly.Global({value:"i32",mutable:!0}));gf.has(b)||(a.required=!0);return a}},hf=[];
function Ca(a){var b=E[a+52>>2];jf(b,b-E[a+56>>2]);K(b)}
var kf=new TextDecoder,lf=(a,b=0,c=NaN)=>{c=b+c;for(var d=b;a[d]&&!(d>=c);)++d;return kf.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(b,d):a.slice(b,d):new Uint8Array(a.slice(b,d)))},mf=a=>{function b(){for(var n=0,q=1;;){var r=a[f++];n+=(r&127)*q;q*=128;if(!(r&128))break}return n}function c(){var n=b();f+=n;return lf(a,f-n,n)}function d(){for(var n=b(),q=[];n--;)q.push(c());return q}function e(n,q){if(n)throw Error(q);}var f=0,g=0;if(a instanceof WebAssembly.Module)g=WebAssembly.Module.customSections(a,
"dylink.0"),e(0===g.length,"need dylink section"),a=new Uint8Array(g[0]),g=a.length;else{g=1836278016==(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0];e(!g,"need to see wasm magic number");e(0!==a[8],"need the dylink section to be first");f=9;g=b();g=f+g;var h=c();e("dylink.0"!==h)}for(h={La:[],mb:new Set,ob:new Set,jb:[]};f<g;){var k=a[f++],l=b();if(1===k)h.Ka=b(),h.Tb=b(),h.sa=b(),h.Mc=b();else if(2===k)h.La=d();else if(3===k)for(k=b();k--;){l=c();var p=b();p&256&&h.mb.add(l)}else if(4===
k)for(k=b();k--;)c(),l=c(),p=b(),1==(p&3)&&h.ob.add(l);else 5===k?h.jb=d():f+=l}return h},nf=[],ob=new WebAssembly.Table({initial:5941,element:"anyfunc"}),P=a=>{var b=nf[a];b||(nf[a]=b=ob.get(a));return b},Ha=(a,b)=>{Se=I=0;of();a=P(a)(b);Se||0<I?qa=a:We(a)},rf=(a,b,c)=>{c={Aa:Infinity,name:a,exports:c,global:!0};pf[a]=c;void 0!=b&&(qf[b]=c);return c},pf={},qf={},nb=3676496,sf=(a,b)=>Math.ceil(a/b)*b,uf=a=>{if(Oa)return tf(a,1);var b=nb;nb=a=b+16*Math.ceil(a/16);ff.__heap_base.value=a;return b},wf=
(a,b)=>{if(vf)for(var c=a;c<a+b;c++){var d=P(c);d&&vf.set(d,c)}},vf,xf=a=>{vf||(vf=new WeakMap,wf(0,ob.length));return vf.get(a)||0},yf=[],zf=(a,b)=>{var c=xf(a);if(c)return c;if(yf.length)c=yf.pop();else{try{ob.grow(1)}catch(k){if(!(k instanceof RangeError))throw k;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}c=ob.length-1}try{var d=c;ob.set(d,a);nf[d]=ob.get(d)}catch(k){if(!(k instanceof TypeError))throw k;if("function"==typeof WebAssembly.Function){d=WebAssembly.Function;for(var e=
{i:"i32",j:"i64",f:"f32",d:"f64",e:"externref",p:"i32"},f={parameters:[],results:"v"==b[0]?[]:[e[b[0]]]},g=1;g<b.length;++g)f.parameters.push(e[b[g]]);b=new d(f,a)}else{d=[1];f=b.slice(0,1);b=b.slice(1);g={i:127,p:127,j:126,f:125,d:124,e:111};d.push(96);var h=b.length;128>h?d.push(h):d.push(h%128|128,h>>7);for(e of b)d.push(g[e]);"v"==f?d.push(0):d.push(1,g[f]);b=[0,97,115,109,1,0,0,0,1];e=d.length;128>e?b.push(e):b.push(e%128|128,e>>7);b.push(...d);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=
new WebAssembly.Module(new Uint8Array(b));b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}d=c;ob.set(d,b);nf[d]=ob.get(d)}vf.set(a,c);return c},Af=(a,b,c)=>{var d={},e;for(e in a){var f=a[e];"object"==typeof f&&(f=f.value);"number"==typeof f&&(f+=b);d[e]=f}for(var g in d){a=g;if("__cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(a)||
a.startsWith("__em_js__"))continue;a=d[g];let h,k;(h=ff)[k=g]||(h[k]=new WebAssembly.Global({value:"i32",mutable:!0}));if(c||0==ff[g].value)"function"==typeof a?ff[g].value=zf(a):"number"==typeof a?ff[g].value=a:v(`unhandled export type for '${g}': ${typeof a}`)}return d},Bf=a=>{a=G[a];return!a||a.G?!1:!0},Cf=(a,b=[])=>P(a)(...b),Df=a=>(b,...c)=>{var d=J();try{return Cf(b,c)}catch(e){K(d);if(!(e instanceof w))throw e;Q(1,0);if("j"==a[0])return 0n}},Ff=a=>{var b;Bf(a)?b=G[a]:a.startsWith("invoke_")?
b=G[a]=Df(a.split("_")[1]):a.startsWith("__cxa_find_matching_catch_")&&(b=G[a]=(...c)=>Ef(c));return{Pa:b,name:a}},Ua=[],R=(a,b)=>{if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&z[c];)++c;return kf.decode(z.slice(a,c))},Kf=(a,b,c,d,e)=>{function f(){function h(x,B){function L(Aa,fa){Aa=[];for(var Na=0;16>Na;Na++)if(-1!=fa.indexOf("$"+Na))Aa.push("$"+Na);else break;Aa=Aa.join(",");Gf[H]=eval(`(${Aa}) => { ${fa} };`)}function M(Aa,fa,Na){var Nf=[];fa=fa.slice(1,-1);if("void"!=fa){fa=fa.split(",");for(var Vh in fa){var Wh=
fa[Vh].split(" ").pop();Nf.push(Wh.replace("*",""))}}q[Aa]=eval(`(${Nf}) => ${Na};`)}!t&&c&&(xa[c]=x);wf(n,g.sa);q=Af(B.exports,p);b.sb||Hf();if("__start_em_asm"in q){var H=q.__start_em_asm;for(x=q.__stop_em_asm;H<x;){var ja=R(H);L(H,ja);H=z.indexOf(0,H)+1}}for(var N in q)N.startsWith("__em_js__")&&(H=q[N],ja=R(H),x=ja.split("<::>"),M(N.replace("__em_js__",""),x[0],x[1]),delete q[N]);If(q._emscripten_tls_init,B.exports,g);k&&((B=q.__wasm_apply_data_relocs)&&(Oa?B():Qa.push(B)),(B=q.__wasm_call_ctors)&&
(Oa?B():Ua.push(B)));return q}var k=!e||!y[e+8];if(k){var l=Math.pow(2,g.Tb),p=g.Ka?sf(uf(g.Ka+l),l):0,n=g.sa?ob.length:0;e&&(y[e+8]=1,E[e+12>>2]=p,D[e+16>>2]=g.Ka,E[e+20>>2]=n,D[e+24>>2]=g.sa)}else p=E[e+12>>2],n=E[e+20>>2];g.sa&&ob.grow(g.sa);var q;l=new Proxy({},{get(x,B){switch(B){case "__memory_base":return p;case "__table_base":return n}if(B in G&&!G[B].G)return G[B];if(!(B in x)){var L;x[B]=(...M)=>{if(!L){var H=Ff(B).Pa;!H&&d&&(H=d[B]);H||=q[B];L=H}return L(...M)}}return x[B]}});var r={"GOT.mem":new Proxy({},
we),"GOT.func":new Proxy({},we),env:l,wasi_snapshot_preview1:l};if(b.H)return(async()=>{var x;a instanceof WebAssembly.Module?x=new WebAssembly.Instance(a,r):{module:a,instance:x}=await WebAssembly.instantiate(a,r);return h(a,x)})();l=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);var u=new WebAssembly.Instance(l,r);return h(l,u)}var g=mf(a);gf=g.ob;b={...b,fc:{Yb:c,ac:g.jb}};if(b.H)return g.La.reduce((h,k)=>h.then(()=>Jf(k,b,d)),Promise.resolve()).then(f);g.La.forEach(h=>Jf(h,b,d));
return f()},Lf=a=>{var b,c;for([b,c]of Object.entries(a))Bf(b)||(G[b]=c)},Mf=async a=>{a=await ia(a);return new Uint8Array(a)},Of=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Pf=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Of(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Qf=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Rf=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Sf=(a,b)=>Pf(a+"/"+b),Tf=a=>{var b=J();a=a();K(b);return a},Uf=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Vf=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=
g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Wf=a=>{var b=Uf(a)+1,c=Qe(b);Vf(a,z,c,b);return c},Xf=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),Yf=a=>{(Yf=Xf())(a)},Zf=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";
b=c+"/"+b;c="/"===c.charAt(0)}b=Of(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},$f=(a,b)=>{function c(g){for(var h=0;h<g.length&&""===g[h];h++);for(var k=g.length-1;0<=k&&""===g[k];k--);return h>k?[]:g.slice(h,k-h+1)}a=Zf(a).slice(1);b=Zf(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},ag=[],bg=a=>{var b=Array(Uf(a)+
1);a=Vf(a,b,0,b.length);b.length=a;return b},cg=[];function dg(a,b){cg[a]={input:[],output:[],ba:b};FS.registerDevice(a,eg)}
var eg={open(a){var b=cg[a.node.qa];if(!b)throw new FS.h(43);a.B=b;a.seekable=!1},close(a){a.B.ba.xa(a.B)},xa(a){a.B.ba.xa(a.B)},read(a,b,c,d){if(!a.B||!a.B.ba.ab)throw new FS.h(60);for(var e=0,f=0;f<d;f++){try{var g=a.B.ba.ab(a.B)}catch(h){throw new FS.h(29);}if(void 0===g&&0===e)throw new FS.h(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.Z=Date.now());return e},write(a,b,c,d){if(!a.B||!a.B.ba.Na)throw new FS.h(60);try{for(var e=0;e<d;e++)a.B.ba.Na(a.B,b[c+e])}catch(f){throw new FS.h(29);
}d&&(a.node.N=a.node.M=Date.now());return e}},fg={ab(){a:{if(!ag.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}ag=bg(a)}a=ag.shift()}return a},Na(a,b){null===b||10===b?(la(lf(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(la(lf(a.output)),a.output=[])},Nb(){return{yc:25856,Ac:5,xc:191,zc:35387,wc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0]}},Ob(){return 0},Pb(){return[24,80]}},gg={Na(a,b){null===b||10===b?(v(lf(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(v(lf(a.output)),a.output=[])}},ig=a=>{a=65536*Math.ceil(a/65536);var b=hg(65536,a);b&&z.fill(0,b,b+a);return b},S={W:null,mount(){return S.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.h(63);S.W||(S.W={dir:{node:{R:S.m.R,T:S.m.T,ha:S.m.ha,aa:S.m.aa,rename:S.m.rename,unlink:S.m.unlink,
rmdir:S.m.rmdir,ra:S.m.ra,symlink:S.m.symlink},stream:{llseek:S.o.llseek}},file:{node:{R:S.m.R,T:S.m.T},stream:{llseek:S.o.llseek,read:S.o.read,write:S.o.write,ia:S.o.ia,ka:S.o.ka}},link:{node:{R:S.m.R,T:S.m.T,readlink:S.m.readlink},stream:{}},Sa:{node:{R:S.m.R,T:S.m.T},stream:FS.vb}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=S.W.dir.node,c.o=S.W.dir.stream,c.u={}):FS.isFile(c.mode)?(c.m=S.W.file.node,c.o=S.W.file.stream,c.D=0,c.u=null):FS.isLink(c.mode)?(c.m=S.W.link.node,c.o=S.W.link.stream):
FS.isChrdev(c.mode)&&(c.m=S.W.Sa.node,c.o=S.W.Sa.stream);c.Z=c.N=c.M=Date.now();a&&(a.u[b]=c,a.Z=a.N=a.M=c.Z);return c},Hc(a){return a.u?a.u.subarray?a.u.subarray(0,a.D):new Uint8Array(a.u):new Uint8Array(0)},m:{R(a){var b={};b.xb=FS.isChrdev(a.mode)?a.id:1;b.Mb=a.id;b.mode=a.mode;b.Ub=1;b.uid=0;b.Ib=0;b.qa=a.qa;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.D:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.Z=new Date(a.Z);b.N=new Date(a.N);b.M=new Date(a.M);b.ub=4096;b.Ra=Math.ceil(b.size/
b.ub);return b},T(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.D!=b&&(0==b?(a.u=null,a.D=0):(c=a.u,a.u=new Uint8Array(b),c&&a.u.set(c.subarray(0,Math.min(b,a.D))),a.D=b)))},ha(){throw S.Wa;},aa(a,b,c,d){return S.createNode(a,b,c,d)},rename(a,b,c){try{var d=jg(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.u)throw new FS.h(55);kg(d)}delete a.parent.u[a.name];b.u[c]=a;a.name=c;b.M=b.N=a.parent.M=a.parent.N=Date.now()},unlink(a,b){delete a.u[b];
a.M=a.N=Date.now()},rmdir(a,b){var c=jg(a,b),d;for(d in c.u)throw new FS.h(55);delete a.u[b];a.M=a.N=Date.now()},ra(a){return[".","..",...Object.keys(a.u)]},symlink(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.h(28);return a.link}},o:{read(a,b,c,d,e){var f=a.node.u;if(e>=a.node.D)return 0;a=Math.min(a.node.D-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;
a.N=a.M=Date.now();if(b.subarray&&(!a.u||a.u.subarray)){if(f)return a.u=b.subarray(c,c+d),a.D=d;if(0===a.D&&0===e)return a.u=b.slice(c,c+d),a.D=d;if(e+d<=a.D)return a.u.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.u?a.u.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.u,a.u=new Uint8Array(f),0<a.D&&a.u.set(g.subarray(0,a.D),0));if(a.u.subarray&&b.subarray)a.u.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.u[e+f]=b[c+f];a.D=Math.max(a.D,e+d);return d},llseek(a,b,c){1===
c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.D);if(0>b)throw new FS.h(28);return b},ia(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.h(43);a=a.node.u;if(e&2||!a||a.buffer!==y.buffer){d=!0;e=ig(b);if(!e)throw new FS.h(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);y.set(a,e)}}else d=!1,e=a.byteOffset;return{s:e,ca:d}},ka(a,b,c,d){S.o.write(a,b,0,d,c,!1);return 0}}},lg=(a,b,c,d)=>{"undefined"!=typeof ef&&bf();var e=!1;Ze.forEach(f=>
{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},mg=(a,b,c,d,e,f,g,h,k,l)=>{function p(r){function u(x){l?.();h||FS.createDataFile(a,b,x,d,e,k);f?.();Ya(q)}lg(r,n,u,()=>{g?.();Ya(q)})||u(r)}var n=b?Zf(Pf(a+"/"+b)):a,q=`cp ${n}`;Xa(q);"string"==typeof c?Mf(c).then(p,g):p(c)},ng=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c};
function jg(a,b){var c=FS.isDir(a.mode)?(c=og(a,"x"))?c:a.m.ha?0:2:54;if(c)throw new FS.h(c);for(c=FS.V[pg(a.id,b)];c;c=c.ja){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.ha(a,b)}function kg(a){var b=pg(a.parent.id,a.name);if(FS.V[b]===a)FS.V[b]=a.ja;else for(b=FS.V[b];b;){if(b.ja===a){b.ja=a.ja;break}b=b.ja}}function pg(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.V.length}function qg(a){var b=pg(a.parent.id,a.name);a.ja=FS.V[b];FS.V[b]=a}
function rg(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function og(a,b){if(FS.bb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function sg(a,b){if(!FS.isDir(a.mode))return 54;try{return jg(a,b),20}catch(c){}return og(a,"wx")}
function tg(a,b,c){try{var d=jg(a,b)}catch(e){return e.A}if(a=og(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.ma(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function ug(a,b){if(!a)throw new FS.h(b);return a}function T(a){a=FS.$a(a);if(!a)throw new FS.h(8);return a}function vg(a,b=-1){a=Object.assign(new FS.qb,a);if(-1==b)a:{for(b=0;b<=FS.rb;b++)if(!FS.streams[b])break a;throw new FS.h(33);}a.$=b;return FS.streams[b]=a}
function wg(a,b=-1){a=vg(a,b);a.o?.Cc?.(a);return a}function xg(a,b,c){var d=a?.o.T;a=d?a:b;d??=b.m.T;ug(d,63);d(a,c)}function yg(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.na)}return b}function zg(a){var b={vc:4096,Fc:4096,Ra:1E6,uc:5E5,tc:5E5,files:FS.Ma,Dc:FS.Ma-1,Gc:42,flags:2,Kc:255};a.m.lb&&Object.assign(b,a.m.lb(a.mount.Wb.root));return b}function Ag(a,b,c,d){xg(a,b,{mode:c&4095|b.mode&-4096,M:Date.now(),Xa:d})}
function Bg(a,b,c){if(FS.isDir(b.mode))throw new FS.h(31);if(!FS.isFile(b.mode))throw new FS.h(28);var d=og(b,"w");if(d)throw new FS.h(d);xg(a,b,{size:c,timestamp:Date.now()})}function Cg(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=Pf(a+"/"+b);return FS.create(b,ng(c,d))}
function Dg(a){if(!(a.Qb||a.Rb||a.link||a.u)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.u=ka(a.url),a.D=a.u.length}catch(b){throw new FS.h(29);}}}
var FS={root:null,na:[],Va:{},streams:[],Ma:1,V:null,Ta:"/",Ga:!1,bb:!0,Cb:null,Ba:0,ib:{},h:class{name="ErrnoError";constructor(a){this.A=a}},qb:class{O={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.O.flags}set flags(a){this.O.flags=a}get position(){return this.O.position}set position(a){this.O.position=a}},pb:class{m={};o={};S=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Ma++;this.name=b;this.mode=c;this.qa=d;this.Z=
this.N=this.M=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Rb(){return FS.isDir(this.mode)}get Qb(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.h(44);b.wa??(b.wa=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;
if("."!==a[f])if(".."===a[f])if(e=Qf(e),FS.ma(d)){a=e+"/"+a.slice(f+1).join("/");continue a}else d=d.parent;else{e=Pf(e+"/"+a[f]);try{d=jg(d,a[f])}catch(h){if(44===h?.A&&g&&b.Vb)return{path:e};throw h;}!d.S||g&&!b.wa||(d=d.S.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.m.readlink)throw new FS.h(52);d=d.m.readlink(d);"/"===d.charAt(0)||(d=Qf(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.h(32);},getPath(a){for(var b;;){if(FS.ma(a))return a=a.mount.fb,
b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.pb(a,b,c,d);qg(a);return a},ma(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},rb:4096,$a:a=>FS.streams[a],vb:{open(a){a.o=FS.Eb(a.node.qa).o;a.o.open?.(a)},llseek(){throw new FS.h(70);}},Ja:a=>a>>
8,Ic:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Va[a]={o:b}},Eb:a=>FS.Va[a],syncfs(a,b){function c(g){FS.Ba--;return b(g)}function d(g){if(g){if(!d.Ab)return d.Ab=!0,c(g)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.Ba++;1<FS.Ba&&v(`warning: ${FS.Ba} FS.syncfs operations in flight at once, probably just doing extra work`);var e=yg(FS.root.mount),f=0;e.forEach(g=>{if(!g.type.syncfs)return d(null);g.type.syncfs(g,a,d)})},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.h(10);
if(!d&&c){var e=FS.lookupPath(c,{wa:!1});c=e.path;e=e.node;if(e.S)throw new FS.h(10);if(!FS.isDir(e.mode))throw new FS.h(54);}b={type:a,Wb:b,fb:c,na:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.S=b,e.mount&&e.mount.na.push(b));return a},unmount(a){a=FS.lookupPath(a,{wa:!1});if(!a.node.S)throw new FS.h(28);a=a.node;var b=a.S,c=yg(b);Object.keys(FS.V).forEach(d=>{for(d=FS.V[d];d;){var e=d.ja;c.includes(d.mount)&&kg(d);d=e}});a.S=null;a.mount.na.splice(a.mount.na.indexOf(b),1)},ha(a,b){return a.m.ha(a,
b)},aa(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=Rf(a);if(!a)throw new FS.h(28);if("."===a||".."===a)throw new FS.h(20);var e=sg(d,a);if(e)throw new FS.h(e);if(!d.m.aa)throw new FS.h(63);return d.m.aa(d,a,b,c)},lb(a){return zg(FS.lookupPath(a,{follow:!0}).node)},Lc(a){return zg(a.node)},create(a,b=438){return FS.aa(a,b&4095|32768,0)},mkdir(a,b=511){return FS.aa(a,b&1023|16384,0)},Jc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=
f.A)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.aa(a,b|8192,c)},symlink(a,b){if(!Zf(a))throw new FS.h(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.h(44);b=Rf(b);var d=sg(c,b);if(d)throw new FS.h(d);if(!c.m.symlink)throw new FS.h(63);return c.m.symlink(c,b,a)},rename(a,b){var c=Qf(a),d=Qf(b),e=Rf(a),f=Rf(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.h(44);if(h.mount!==g.mount)throw new FS.h(75);
var k=jg(h,e);a=$f(a,d);if("."!==a.charAt(0))throw new FS.h(28);a=$f(b,c);if("."!==a.charAt(0))throw new FS.h(55);try{var l=jg(g,f)}catch(p){}if(k!==l){b=FS.isDir(k.mode);if(e=tg(h,e,b))throw new FS.h(e);if(e=l?tg(g,f,b):sg(g,f))throw new FS.h(e);if(!h.m.rename)throw new FS.h(63);if(k.S||l&&l.S)throw new FS.h(10);if(g!==h&&(e=og(h,"w")))throw new FS.h(e);kg(k);try{h.m.rename(k,g,f),k.parent=g}catch(p){throw p;}finally{qg(k)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=Rf(a);var c=jg(b,a),
d=tg(b,a,!0);if(d)throw new FS.h(d);if(!b.m.rmdir)throw new FS.h(63);if(c.S)throw new FS.h(10);b.m.rmdir(b,a);kg(c)},ra(a){a=FS.lookupPath(a,{follow:!0}).node;return ug(a.m.ra,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.h(44);a=Rf(a);var c=jg(b,a),d=tg(b,a,!1);if(d)throw new FS.h(d);if(!b.m.unlink)throw new FS.h(63);if(c.S)throw new FS.h(10);b.m.unlink(b,a);kg(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.h(44);if(!a.m.readlink)throw new FS.h(28);return a.m.readlink(a)},
stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return ug(a.m.R,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;Ag(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=T(a);Ag(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;xg(null,a,{timestamp:Date.now(),Xa:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=T(a);xg(a,a.node,{timestamp:Date.now(),Xa:!1})},truncate(a,b){if(0>b)throw new FS.h(28);
a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;Bg(null,a,b)},ftruncate(a,b){a=T(a);if(0>b||0===(a.flags&2097155))throw new FS.h(28);Bg(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;ug(a.m.T,63)(a,{Z:b,N:c})},open(a,b,c=438){if(""===a)throw new FS.h(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");
a=FS.lookupPath(a,{follow:!(b&131072),Vb:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new FS.h(20);}else{if(e)throw new FS.h(31);d=FS.aa(a,c|511,0);f=!0}if(!d)throw new FS.h(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.h(54);if(!f){e=d;var g=b;if(e=e?FS.isLink(e.mode)?32:FS.isDir(e.mode)&&("r"!==rg(g)||g&576)?31:og(e,rg(g)):44)throw new FS.h(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;e=vg({node:d,path:FS.getPath(d),flags:b,seekable:!0,position:0,o:d.o,
pc:[],error:!1});e.o.open&&e.o.open(e);f&&FS.chmod(d,c&511);!m.logReadFiles||b&1||a in FS.ib||(FS.ib[a]=1);return e},close(a){if(null===a.$)throw new FS.h(8);a.Ea&&(a.Ea=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.$]=null}a.$=null},llseek(a,b,c){if(null===a.$)throw new FS.h(8);if(!a.seekable||!a.o.llseek)throw new FS.h(70);if(0!=c&&1!=c&&2!=c)throw new FS.h(28);a.position=a.o.llseek(a,b,c);a.pc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.h(28);if(null===
a.$)throw new FS.h(8);if(1===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.read)throw new FS.h(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.h(28);if(null===a.$)throw new FS.h(8);if(0===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.write)throw new FS.h(28);a.seekable&&a.flags&1024&&
FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},ia(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.h(2);if(1===(a.flags&2097155))throw new FS.h(2);if(!a.o.ia)throw new FS.h(43);if(!b)throw new FS.h(28);return a.o.ia(a,b,c,d,e)},ka(a,b,c,d,e){return a.o.ka?a.o.ka(a,b,c,d,e):0},Ha(a,b,c){if(!a.o.Ha)throw new FS.h(59);return a.o.Ha(a,b,c)},readFile(a,b={}){b.flags=b.flags||
0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=lf(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(bg(b)));if(ArrayBuffer.isView(b))FS.write(a,b,0,b.byteLength,void 0,c.Bc);else throw Error("Unsupported data type");FS.close(a)},
cwd:()=>FS.Ta,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.h(44);if(!FS.isDir(a.node.mode))throw new FS.h(54);var b=og(a.node,"x");if(b)throw new FS.h(b);FS.Ta=a.path},init(a,b,c){FS.Ga=!0;a??=m.stdin;b??=m.stdout;c??=m.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",
0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Ec(a,b){a=FS.analyzePath(a,b);return a.Ya?a.object:null},analyzePath(a,b){try{var c=FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={ma:!1,Ya:!1,error:0,name:null,path:null,object:null,Xb:!1,$b:null,Zb:null};try{c=FS.lookupPath(a,{parent:!0}),d.Xb=!0,d.$b=c.path,d.Zb=c.node,d.name=Rf(a),c=FS.lookupPath(a,{follow:!b}),d.Ya=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.ma="/"===c.path}catch(e){d.error=e.A}return d},createPath(a,b){a=
"string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Pf(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=e.A)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?Pf(a+"/"+b):a);a=ng(d,e);g=FS.create(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}FS.chmod(g,a|146);b=FS.open(g,577);FS.write(b,c,0,c.length,0,f);FS.close(b);FS.chmod(g,a)}},createDevice(a,
b,c,d){a=Sf("string"==typeof a?a:FS.getPath(a),b);b=ng(!!c,!!d);var e;(e=FS.createDevice).Ja??(e.Ja=64);e=FS.makedev(FS.createDevice.Ja++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,k){for(var l=0,p=0;p<k;p++){try{var n=c()}catch(q){throw new FS.h(29);}if(void 0===n&&0===l)throw new FS.h(6);if(null===n||void 0===n)break;l++;g[h+p]=n}l&&(f.node.Z=Date.now());return l},write(f,g,h,k){for(var l=0;l<k;l++)try{d(g[h+l])}catch(p){throw new FS.h(29);}k&&(f.node.N=
f.node.M=Date.now());return l}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(n,q,r,u,x){n=n.node.u;if(x>=n.length)return 0;u=Math.min(n.length-x,u);if(n.slice)for(var B=0;B<u;B++)q[r+B]=n[x+B];else for(B=0;B<u;B++)q[r+B]=n.get(x+B);return u}class g{Fa=!1;O=[];la=void 0;eb=0;cb=0;get(n){if(!(n>this.length-1||0>n)){var q=n%this.kb;return this.la(n/this.kb|0)[q]}}oc(n){this.la=n}gb(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+
c+". Status: "+n.status);var q=Number(n.getResponseHeader("Content-length")),r,u=(r=n.getResponseHeader("Accept-Ranges"))&&"bytes"===r;n=(r=n.getResponseHeader("Content-Encoding"))&&"gzip"===r;var x=1048576;u||(x=q);var B=this;B.oc(L=>{var M=L*x,H=(L+1)*x-1;H=Math.min(H,q-1);if("undefined"==typeof B.O[L]){var ja=B.O;if(M>H)throw Error("invalid range ("+M+", "+H+") or no bytes requested!");if(H>q-1)throw Error("only "+q+" bytes available! programmer error!");var N=new XMLHttpRequest;N.open("GET",c,
!1);q!==x&&N.setRequestHeader("Range","bytes="+M+"-"+H);N.responseType="arraybuffer";N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);if(!(200<=N.status&&300>N.status||304===N.status))throw Error("Couldn't load "+c+". Status: "+N.status);M=void 0!==N.response?new Uint8Array(N.response||[]):bg(N.responseText||"");ja[L]=M}if("undefined"==typeof B.O[L])throw Error("doXHR failed!");return B.O[L]});if(n||!q)x=q=1,x=q=this.la(0).length,la("LazyFiles on gzip forces download of the whole file when length is accessed");
this.eb=q;this.cb=x;this.Fa=!0}get length(){this.Fa||this.gb();return this.eb}get kb(){this.Fa||this.gb();return this.cb}}if("undefined"!=typeof XMLHttpRequest){if(!ba)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;var k=void 0}else k=c,h=void 0;var l=Cg(a,b,d,e);h?l.u=h:k&&(l.u=null,l.url=k);Object.defineProperties(l,{D:{get:function(){return this.u.length}}});var p={};Object.keys(l.o).forEach(n=>{var q=l.o[n];
p[n]=(...r)=>{Dg(l);return q(...r)}});p.read=(n,q,r,u,x)=>{Dg(l);return f(n,q,r,u,x)};p.ia=(n,q,r)=>{Dg(l);var u=ig(q);if(!u)throw new FS.h(48);f(n,y,u,q,r);return{s:u,ca:!0}};l.o=p;return l}},Fg=(a,b)=>{if(Oa){if("/"===a.charAt(0))try{return FS.lookupPath(a),a}catch(d){return}var c=(b?.ac||[]).map(d=>{var e=b?.Yb;return d.startsWith("$ORIGIN")?d.replace("$ORIGIN",Qf(e)):d});return Tf(()=>{var d=Qe(512),e=Wf(c.join(":")),f=Wf(a);return(d=Eg(d,e,f,512))?R(d):void 0})}};
function Jf(a,b={global:!0,oa:!0},c,d){function e(){var k=xa[a];if(k)return b.H?Promise.resolve(k):k;if(d){k=E[d+28>>2];var l=E[d+32>>2];if(k&&l)return k=y.slice(k,k+l),b.H?Promise.resolve(k):k}if(k=Fg(a,b.fc))return k=FS.readFile(k,{encoding:"binary"}),b.H?Promise.resolve(k):k;k=ha(a);if(b.H)return Mf(k);if(!ka)throw Error(`${k}: file not found, and synchronous loading of external files is not available`);return ka(k)}function f(){var k=$e[a];return k?b.H?Promise.resolve(k):k:b.H?e().then(l=>Kf(l,
b,a,c,d)):Kf(e(),b,a,c,d)}function g(k){h.global?Lf(k):c&&Object.assign(c,k);h.exports=k}var h=pf[a];if(h)return b.global?h.global||(h.global=!0,Lf(h.exports)):c&&Object.assign(c,h.exports),b.oa&&Infinity!==h.Aa&&(h.Aa=Infinity),h.Aa++,d&&(qf[d]=h),b.H?Promise.resolve(!0):!0;h=rf(a,d,"loading");h.Aa=b.oa?Infinity:1;h.global=b.global;if(b.H)return f().then(k=>{g(k);return!0});g(f());return!0}
var Hf=()=>{var a,b;for([a,b]of Object.entries(ff))if(0==b.value){var c=Ff(a).Pa;if(c||b.required)if("function"==typeof c)b.value=zf(c,c.g);else if("number"==typeof c)b.value=c;else throw Error(`bad export type for '${a}': ${typeof c}`);}},Gg=()=>{ma.length?(Xa("loadDylibs"),ma.reduce((a,b)=>a.then(()=>Jf(b,{H:!0,global:!0,oa:!0,sb:!0})),Promise.resolve()).then(()=>{Hf();Ya("loadDylibs")})):Hf()},Se=!1,If=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.mb.forEach(g=>f[g]=b[g]);Af(f,e,!0)}}Le.push(d);
Oa&&d()},eb=(a,b,c,d)=>Za(`Assertion failed: ${R(a)}, at: `+[b?R(b):"unknown filename",c,d?R(d):"unknown function"]);eb.g="vppip";var fb=(a,b)=>P(a)(b);fb.g="vpi";var Hg=[],Ig=0,gb=a=>{var b=new Jg(a);0==y[b.s+12]&&(y[b.s+12]=1,Ig--);y[b.s+13]=0;Hg.push(b);Kg(a);return Lg(a)};gb.g="pp";var Mg=0,hb=()=>{Q(0,0);var a=Hg.pop();Ng(a.va);Mg=0};hb.g="v";class Jg{constructor(a){this.va=a;this.s=a-24}init(a,b){E[this.s+16>>2]=0;E[this.s+4>>2]=a;E[this.s+8>>2]=b}}
var Ef=a=>{var b=Mg?.va;if(!b)return Og(0),0;var c=new Jg(b);E[c.s+16>>2]=b;var d=E[c.s+4>>2];if(!d)return Og(0),b;for(var e of a){if(0===e||e===d)break;if(Pg(e,d,c.s+16))return Og(e),b}Og(d);return b},ib=()=>Ef([]);ib.g="p";var jb=a=>Ef([a]);jb.g="pp";var kb=()=>{var a=Hg.pop();a||Za("no exception to throw");var b=a.va;0==y[a.s+13]&&(Hg.push(a),y[a.s+13]=1,y[a.s+12]=0,Ig++);Mg=new sa(b);throw Mg;};kb.g="v";var lb=(a,b,c)=>{(new Jg(a)).init(b,c);Mg=new sa(a);Ig++;throw Mg;};lb.g="vppp";
var mb=()=>Ig;mb.g="i";function pb(...a){return G.__lsan_ignore_object(...a)}pb.G=!0;var qb=new WebAssembly.Global({value:"i32",mutable:!1},1024);function Qg(a,b,c,d){return t?O(2,1,a,b,c,d):rb(a,b,c,d)}var rb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(t&&0===e.length)return Qg(a,b,c,d);a={mc:c,X:a,Da:d,nb:e};return t?(a.U="spawnThread",postMessage(a,e),0):Ke(a)};rb.g="ipppp";var sb=a=>{Mg||=new sa(a);throw Mg;};sb.g="vp";
var tb=3676496,ub=3414352,vb=new WebAssembly.Global({value:"i32",mutable:!0},3676496),Rg=5;function Sg(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():T(a).path;if(0==b.length){if(!c)throw new FS.h(44);return a}return a+"/"+b}
function Tg(a,b){D[a>>2]=b.xb;D[a+4>>2]=b.mode;E[a+8>>2]=b.Ub;D[a+12>>2]=b.uid;D[a+16>>2]=b.Ib;D[a+20>>2]=b.qa;F[a+24>>3]=BigInt(b.size);D[a+32>>2]=4096;D[a+36>>2]=b.Ra;var c=b.Z.getTime(),d=b.N.getTime(),e=b.M.getTime();F[a+40>>3]=BigInt(Math.floor(c/1E3));E[a+48>>2]=c%1E3*1E6;F[a+56>>3]=BigInt(Math.floor(d/1E3));E[a+64>>2]=d%1E3*1E6;F[a+72>>3]=BigInt(Math.floor(e/1E3));E[a+80>>2]=e%1E3*1E6;F[a+88>>3]=BigInt(b.Mb);return 0}var Ug=void 0;
function wb(a){if(t)return O(3,1,a);try{var b=T(a);return wg(b).$}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}wb.g="ii";function xb(a,b,c,d){if(t)return O(4,1,a,b,c,d);try{b=R(b);b=Sg(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&og(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}xb.g="iipii";var Vg=()=>{var a=D[+Ug>>2];Ug+=4;return a};
function yb(a,b,c){if(t)return O(5,1,a,b,c);Ug=c;try{var d=T(a);switch(b){case 0:var e=Vg();if(0>e)break;for(;FS.streams[e];)e++;return wg(d,e).$;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Vg(),d.flags|=e,0;case 12:return e=Vg(),A[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}yb.g="iiip";
function zb(a,b){if(t)return O(6,1,a,b);try{var c=T(a),d=c.node,e=c.o.R;a=e?c:d;e??=d.m.R;ug(e,63);var f=e(a);return Tg(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.A}}zb.g="iip";function Ab(a,b){if(t)return O(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-61;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}Ab.g="iij";
function Bb(a,b){if(t)return O(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=Uf(c)+1;if(b<d)return-68;Vf(c,z,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.A}}Bb.g="ipp";
function Cb(a,b,c){if(t)return O(9,1,a,b,c);Ug=c;try{var d=T(a);switch(b){case 21509:return d.B?0:-59;case 21505:if(!d.B)return-59;if(d.B.ba.Nb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Vg();D[e>>2]=25856;D[e+4>>2]=5;D[e+8>>2]=191;D[e+12>>2]=35387;for(var f=0;32>f;f++)y[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.B?0:-59;case 21506:case 21507:case 21508:if(!d.B)return-59;if(d.B.ba.Ob)for(e=Vg(),a=[],f=0;32>f;f++)a.push(y[e+f+17]);
return 0;case 21519:if(!d.B)return-59;e=Vg();return D[e>>2]=0;case 21520:return d.B?-28:-59;case 21531:return e=Vg(),FS.Ha(d,b,e);case 21523:if(!d.B)return-59;d.B.ba.Pb&&(f=[24,80],e=Vg(),A[e>>1]=f[0],A[e+2>>1]=f[1]);return 0;case 21524:return d.B?0:-59;case 21515:return d.B?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.A}}Cb.g="iiip";
function Db(a,b){if(t)return O(10,1,a,b);try{return a=R(a),Tg(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}Db.g="ipp";function Eb(a,b,c,d){if(t)return O(11,1,a,b,c,d);try{b=R(b);var e=d&256;b=Sg(a,b,d&4096);return Tg(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}Eb.g="iippi";
function Fb(a,b,c,d){if(t)return O(12,1,a,b,c,d);Ug=d;try{b=R(b);b=Sg(a,b);var e=d?Vg():0;return FS.open(b,c,e).$}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.A}}Fb.g="iipip";function Gb(a,b,c){if(t)return O(13,1,a,b,c);try{for(var d=c=0;d<b;d++){var e=a+8*d,f=A[e+4>>1],g=32,h=FS.$a(D[e>>2]);h&&(g=Rg,h.o.cc&&(g=h.o.cc(h,-1)));(g&=f|24)&&c++;A[e+6>>1]=g}return c}catch(k){if("undefined"==typeof FS||"ErrnoError"!==k.name)throw k;return-k.A}}Gb.g="ipii";
function Hb(a){if(t)return O(14,1,a);try{return a=R(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.A}}Hb.g="ip";function Ib(a,b){if(t)return O(15,1,a,b);try{return a=R(a),Tg(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.A}}Ib.g="ipp";
function Jb(a,b,c){if(t)return O(16,1,a,b,c);try{b=R(b);b=Sg(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.A}}Jb.g="iipi";var Kb=new WebAssembly.Global({value:"i32",mutable:!1},1),Lb=()=>Za("");Lb.g="v";
var Xg=a=>{var b=J();a=Wf(a);Wg(a,0);K(b)},Yg=(a,b)=>{var c=R(a+36),d=D[a+4>>2];c=Pf(c);var e=!!(d&256),f=e?null:{};d={global:e,oa:!!(d&4096),H:b.H};if(b.H)return Jf(c,d,f,a);try{return Jf(c,d,f,a)}catch(g){return Xg(`Could not load dynamic lib: ${c}\n${g}`),0}},Mb=a=>Yg(a,{H:!1});Mb.g="pp";var Nb=(a,b)=>{a=qf[a].exports;b=Object.keys(a)[b];b=a[b];return zf(b,b.g)};Nb.g="ppi";
var Ob=(a,b,c)=>{b=R(b);var d=qf[a];if(!d.exports.hasOwnProperty(b)||d.exports[b].G)return Xg(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;a=Object.keys(d.exports).indexOf(b);b=d.exports[b];"function"==typeof b&&((d=xf(b))?b=d:(b=zf(b,b.g),E[c>>2]=a));return b};Ob.g="pppp";var Zg={},$g=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function ah(a){return this.fromWireType(E[a>>2])}
var bh={},ch={},dh={},eh=class extends Error{constructor(a){super(a);this.name="InternalError"}},fh=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new eh("Mismatched type converter count");for(var k=0;k<a.length;++k)U(a[k],h[k])}a.forEach(h=>dh[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,k)=>{ch.hasOwnProperty(h)?e[k]=ch[h]:(f.push(h),bh.hasOwnProperty(h)||(bh[h]=[]),bh[h].push(()=>{e[k]=ch[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},Pb=a=>{var b=Zg[a];delete Zg[a];var c=
b.Oa,d=b.Y,e=b.Za,f=e.map(g=>g.Hb).concat(e.map(g=>g.ic));fh([a],f,g=>{var h={};e.forEach((k,l)=>{var p=g[l],n=k.la,q=k.Gb,r=g[l+e.length],u=k.hc,x=k.jc;h[k.Bb]={read:B=>p.fromWireType(n(q,B)),write:(B,L)=>{var M=[];u(x,B,r.toWireType(M,L));$g(M)},optional:g[l].optional}});return[{name:b.name,fromWireType:k=>{var l={},p;for(p in h)l[p]=h[p].read(k);d(k);return l},toWireType:(k,l)=>{for(var p in h)if(!(p in l||h[p].optional))throw new TypeError(`Missing field: "${p}"`);var n=c();for(p in h)h[p].write(n,
l[p]);null!==k&&k.push(d,n);return n},K:gh,readValueFromPointer:ah,J:d}]})};Pb.g="vp";var V=a=>{for(var b="";;){var c=z[a++];if(!c)return b;b+=String.fromCharCode(c)}},W=class extends Error{constructor(a){super(a);this.name="BindingError"}},hh=a=>{throw new W(a);};
function ih(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if(ch.hasOwnProperty(a)){if(c.Lb)return;throw new W(`Cannot register type '${d}' twice`);}ch[a]=b;delete dh[a];bh.hasOwnProperty(a)&&(b=bh[a],delete bh[a],b.forEach(e=>e()))}function U(a,b,c={}){return ih(a,b,c)}
var Qb=(a,b,c,d,e)=>{b=V(b);if(d)a:switch(c){case 4:d=Ka;break a;case 8:d=La;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?y:z;break a;case 2:d=e?A:C;break a;case 4:d=e?D:E;break a;case 8:d=e?F:Ma;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);}var f=d,g=Math.log2(c);U(a,{name:b,fromWireType:h=>{var k=h+Math.max(4,c)>>g;k=Array.from(f.subarray(k,k+E[h>>2]));X(h);return k},toWireType:(h,k)=>{"number"==typeof k&&(k=[k]);
if(!Array.isArray(k))throw new W(`Cannot pass non-array to C++ vector type ${b}`);k=Array.prototype.concat.apply([],k);var l=k.length,p=Math.max(4,c),n=jh(p+l*c);p=n+p>>g;E[n>>2]=l;f.set(k,p);null!==h&&h.push(X,n);return n},K:gh,readValueFromPointer:ah,J(h){X(h)}})};Qb.g="vpppii";
var kh=(a,b,c)=>{switch(b){case 1:return c?d=>y[d]:d=>z[d];case 2:return c?d=>A[d>>1]:d=>C[d>>1];case 4:return c?d=>D[d>>2]:d=>E[d>>2];case 8:return c?d=>F[d>>3]:d=>Ma[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Rb=(a,b,c,d,e)=>{b=V(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}U(a,{name:b,fromWireType:f,toWireType:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},K:gh,readValueFromPointer:kh(b,c,!d),J:null})};Rb.g="vpppjj";
var gh=8,Sb=(a,b,c,d)=>{b=V(b);U(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},K:gh,readValueFromPointer:function(e){return this.fromWireType(z[e])},J:null})};Sb.g="vppii";
var lh=a=>{throw new W(a.l.C.v.name+" instance already deleted");},mh=!1,nh=!1,oh=()=>{},ph=a=>{if(mh)return ph=b=>b.deleteLater(),ph(a);if("undefined"===typeof FinalizationRegistry)return ph=b=>b,a;nh=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.I?b.P.Y(b.I):b.C.v.Y(b.s))});ph=b=>{var c=b.l;c.I&&nh.register(b,{l:c},b);return b};oh=b=>{nh.unregister(b)};return ph(a)},qh=[],rh=()=>{for(;qh.length;){var a=qh.pop();a.l.ga=!1;a["delete"]()}},sh;function th(){}
var uh=(a,b)=>Object.defineProperty(b,"name",{value:a}),vh={},wh=(a,b,c)=>{if(void 0===a[b].F){var d=a[b];a[b]=function(...e){if(!a[b].F.hasOwnProperty(e.length))throw new W(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].F})!`);return a[b].F[e.length].apply(this,e)};a[b].F=[];a[b].F[d.ea]=d}},xh=(a,b,c)=>{if(m.hasOwnProperty(a)){if(void 0===c||void 0!==m[a].F&&void 0!==m[a].F[c])throw new W(`Cannot register public name '${a}' twice`);wh(m,a,a);if(m[a].F.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
m[a].F[c]=b}else m[a]=b,m[a].ea=c},yh=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function zh(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.da=c;this.Y=d;this.L=e;this.Db=f;this.ta=g;this.yb=h;this.dc=[]}
var Ah=(a,b,c)=>{for(;b!==c;){if(!b.ta)throw new W(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ta(a);b=b.L}return a},Bh=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function Ch(a,b){if(null===b){if(this.Ia)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${Bh(b)}" as a ${this.name}`);if(!b.l.s)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);return Ah(b.l.s,b.l.C.v,this.v)}
function Dh(a,b){if(null===b){if(this.Ia)throw new W(`null is not a valid ${this.name}`);if(this.za){var c=this.Oa();null!==a&&a.push(this.Y,c);return c}return 0}if(!b||!b.l)throw new W(`Cannot pass "${Bh(b)}" as a ${this.name}`);if(!b.l.s)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ya&&b.l.C.ya)throw new W(`Cannot convert argument of type ${b.l.P?b.l.P.name:b.l.C.name} to parameter type ${this.name}`);c=Ah(b.l.s,b.l.C.v,this.v);if(this.za){if(void 0===b.l.I)throw new W("Passing raw pointer to smart pointer is illegal");
switch(this.lc){case 0:if(b.l.P===this)c=b.l.I;else throw new W(`Cannot convert argument of type ${b.l.P?b.l.P.name:b.l.C.name} to parameter type ${this.name}`);break;case 1:c=b.l.I;break;case 2:if(b.l.P===this)c=b.l.I;else{var d=b.clone();c=this.ec(c,Eh(()=>d["delete"]()));null!==a&&a.push(this.Y,c)}break;default:throw new W("Unsupporting sharing policy");}}return c}
function Fh(a,b){if(null===b){if(this.Ia)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${Bh(b)}" as a ${this.name}`);if(!b.l.s)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.C.ya)throw new W(`Cannot convert argument of type ${b.l.C.name} to parameter type ${this.name}`);return Ah(b.l.s,b.l.C.v,this.v)}
var Gh=(a,b,c)=>{if(b===c)return a;if(void 0===c.L)return null;a=Gh(a,b,c.L);return null===a?null:c.yb(a)},Hh={},Ih=(a,b)=>{if(void 0===b)throw new W("ptr should not be undefined");for(;a.L;)b=a.ta(b),a=a.L;return Hh[b]},Jh=(a,b)=>{if(!b.C||!b.s)throw new eh("makeClassHandle requires ptr and ptrType");if(!!b.P!==!!b.I)throw new eh("Both smartPtrType and smartPtr must be specified");b.count={value:1};return ph(Object.create(a,{l:{value:b,writable:!0}}))};
function Kh(a,b,c,d,e,f,g,h,k,l,p){this.name=a;this.v=b;this.Ia=c;this.ya=d;this.za=e;this.bc=f;this.lc=g;this.hb=h;this.Oa=k;this.ec=l;this.Y=p;e||void 0!==b.L?this.toWireType=Dh:(this.toWireType=d?Ch:Fh,this.J=null)}var Lh=(a,b,c)=>{if(!m.hasOwnProperty(a))throw new eh("Replacing nonexistent public symbol");void 0!==m[a].F&&void 0!==c?m[a].F[c]=b:(m[a]=b,m[a].ea=c)},Y=(a,b)=>{a=V(a);var c=P(b);if("function"!=typeof c)throw new W(`unknown function pointer with signature ${a}: ${b}`);return c};
class Mh extends Error{}
var Oh=a=>{a=Nh(a);var b=V(a);X(a);return b},Ph=(a,b)=>{function c(f){e[f]||ch[f]||(dh[f]?dh[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Mh(`${a}: `+d.map(Oh).join([", "]));},Tb=(a,b,c,d,e,f,g,h,k,l,p,n,q)=>{p=V(p);f=Y(e,f);h&&=Y(g,h);l&&=Y(k,l);q=Y(n,q);var r=yh(p);xh(r,function(){Ph(`Cannot construct ${p} due to unbound types`,[d])});fh([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var x=u.v;var B=x.da}else B=th.prototype;u=uh(p,function(...ja){if(Object.getPrototypeOf(this)!==L)throw new W(`Use 'new' to construct ${p}`);
if(void 0===M.fa)throw new W(`${p} has no accessible constructor`);var N=M.fa[ja.length];if(void 0===N)throw new W(`Tried to invoke ctor of ${p} with invalid number of parameters (${ja.length}) - expected (${Object.keys(M.fa).toString()}) parameters instead!`);return N.apply(this,ja)});var L=Object.create(B,{constructor:{value:u}});u.prototype=L;var M=new zh(p,u,L,q,x,f,h,l);if(M.L){var H;(H=M.L).ua??(H.ua=[]);M.L.ua.push(M)}x=new Kh(p,M,!0,!1,!1);H=new Kh(p+"*",M,!1,!1,!1);B=new Kh(p+" const*",M,
!1,!0,!1);vh[a]={pointerType:H,wb:B};Lh(r,u);return[x,H,B]})};Tb.g="vppppppppppppp";function Qh(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].J)return!0;return!1}
function Rh(a,b,c,d,e,f){var g=b.length;if(2>g)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=Qh(b);c="void"!==b[0].name;d=[a,hh,d,e,$g,b[0],b[1]];for(e=0;e<g-2;++e)d.push(b[e+2]);if(!k)for(e=h?1:2;e<b.length;++e)null!==b[e].J&&d.push(b[e].J);k=Qh(b);e=b.length-2;var l=[],p=["fn"];h&&p.push("thisWired");for(g=0;g<e;++g)l.push(`arg${g}`),p.push(`arg${g}Wired`);l=l.join(",");p=p.join(",");l=`return function (${l}) {\n`;k&&
(l+="var destructors = [];\n");var n=k?"destructors":"null",q="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");h&&(l+=`var thisWired = classParam['toWireType'](${n}, this);\n`);for(g=0;g<e;++g)l+=`var arg${g}Wired = argType${g}['toWireType'](${n}, arg${g});\n`,q.push(`argType${g}`);l+=(c||f?"var rv = ":"")+`invoker(${p});\n`;if(k)l+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].J&&(l+=`${f}_dtor(${f});\n`,
q.push(`${f}_dtor`));c&&(l+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [r,u]=[q,l+"}\n"];b=(new Function(...r,u))(...d);return uh(a,b)}
var Sh=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+4*d>>2]);return c},Th=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Ub=(a,b,c,d,e,f,g,h)=>{var k=Sh(c,d);b=V(b);b=Th(b);f=Y(e,f);fh([],[a],l=>{function p(){Ph(`Cannot call ${n} due to unbound types`,k)}l=l[0];var n=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var q=l.v.constructor;void 0===q[b]?(p.ea=c-1,q[b]=p):(wh(q,b,n),q[b].F[c-1]=p);fh([],k,r=>{r=Rh(n,[r[0],null].concat(r.slice(1)),null,f,g,h);void 0===
q[b].F?(r.ea=c-1,q[b]=r):q[b].F[c-1]=r;if(l.v.ua)for(const u of l.v.ua)u.constructor.hasOwnProperty(b)||(u.constructor[b]=r);return[]});return[]})};Ub.g="vppippppii";
var Vb=(a,b,c,d,e,f)=>{var g=Sh(b,c);e=Y(d,e);fh([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.v.fa&&(h.v.fa=[]);if(void 0!==h.v.fa[b-1])throw new W(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.v.fa[b-1]=()=>{Ph(`Cannot construct ${h.name} due to unbound types`,g)};fh([],g,l=>{l.splice(1,0,null);h.v.fa[b-1]=Rh(k,l,null,e,f);
return[]});return[]})};Vb.g="vpipppp";
var Wb=(a,b,c,d,e,f,g,h,k)=>{var l=Sh(c,d);b=V(b);b=Th(b);f=Y(e,f);fh([],[a],p=>{function n(){Ph(`Cannot call ${q} due to unbound types`,l)}p=p[0];var q=`${p.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&p.v.dc.push(b);var r=p.v.da,u=r[b];void 0===u||void 0===u.F&&u.className!==p.name&&u.ea===c-2?(n.ea=c-2,n.className=p.name,r[b]=n):(wh(r,b,q),r[b].F[c-2]=n);fh([],l,x=>{x=Rh(q,x,p,f,g,k);void 0===r[b].F?(x.ea=c-2,r[b]=x):r[b].F[c-2]=x;return[]});return[]})};Wb.g="vppippppiii";
var Uh=(a,b,c)=>{if(!(a instanceof Object))throw new W(`${c} with invalid "this": ${a}`);if(!(a instanceof b.v.constructor))throw new W(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.s)throw new W(`cannot call emscripten binding method ${c} on deleted object`);return Ah(a.l.s,a.l.C.v,b.v)},Xb=(a,b,c,d,e,f,g,h,k,l)=>{b=V(b);e=Y(d,e);fh([],[a],p=>{p=p[0];var n=`${p.name}.${b}`,q={get(){Ph(`Cannot access ${n} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};q.set=
k?()=>Ph(`Cannot access ${n} due to unbound types`,[c,g]):()=>{throw new W(n+" is a read-only property");};Object.defineProperty(p.v.da,b,q);fh([],k?[c,g]:[c],r=>{var u=r[0],x={get(){var L=Uh(this,p,n+" getter");return u.fromWireType(e(f,L))},enumerable:!0};if(k){k=Y(h,k);var B=r[1];x.set=function(L){var M=Uh(this,p,n+" setter"),H=[];k(l,M,B.toWireType(H,L));$g(H)}}Object.defineProperty(p.v.da,b,x);return[]});return[]})};Xb.g="vpppppppppp";
var Xh=[],Yh=[0,1,,1,null,1,!0,1,!1,1],xc=a=>{9<a&&0===--Yh[a+1]&&(Yh[a]=void 0,Xh.push(a))};xc.g="vp";var Z=a=>{if(!a)throw new W(`Cannot use deleted val. handle = ${a}`);return Yh[a]},Eh=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Xh.pop()||Yh.length;Yh[b]=a;Yh[b+1]=1;return b}},Zh={name:"emscripten::val",fromWireType:a=>{var b=Z(a);xc(a);return b},toWireType:(a,b)=>Eh(b),K:gh,readValueFromPointer:ah,J:null},Yb=a=>U(a,Zh);Yb.g="vp";
var $h=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.fromWireType(y[d])}:function(d){return this.fromWireType(z[d])};case 2:return c?function(d){return this.fromWireType(A[d>>1])}:function(d){return this.fromWireType(C[d>>1])};case 4:return c?function(d){return this.fromWireType(D[d>>2])}:function(d){return this.fromWireType(E[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Zb=(a,b,c,d)=>{function e(){}b=V(b);e.values={};U(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},
toWireType:(f,g)=>g.value,K:gh,readValueFromPointer:$h(b,c,d),J:null});xh(b,e)};Zb.g="vpppi";var ai=(a,b)=>{var c=ch[a];if(void 0===c)throw a=`${b} has unknown type ${Oh(a)}`,new W(a);return c},$b=(a,b,c)=>{var d=ai(a,"enum");b=V(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:uh(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d};$b.g="vppi";
var bi=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(Ka[c>>2])};case 8:return function(c){return this.fromWireType(La[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},ac=(a,b,c)=>{b=V(b);U(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,K:gh,readValueFromPointer:bi(b,c),J:null})};ac.g="vppp";
var bc=(a,b,c,d,e,f,g)=>{var h=Sh(b,c);a=V(a);a=Th(a);e=Y(d,e);xh(a,function(){Ph(`Cannot call ${a} due to unbound types`,h)},b-1);fh([],h,k=>{Lh(a,Rh(a,[k[0],null].concat(k.slice(1)),null,e,f,g),b-1);return[]})};bc.g="vpippppii";var cc=(a,b,c,d,e)=>{b=V(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}U(a,{name:b,fromWireType:f,toWireType:(h,k)=>k,K:gh,readValueFromPointer:kh(b,c,0!==d),J:null})};cc.g="vpppii";
var dc=(a,b,c)=>{function d(f){return new e(y.buffer,E[f+4>>2],E[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=V(c);U(a,{name:c,fromWireType:d,K:gh,readValueFromPointer:d},{Lb:!0})};dc.g="vpip";
var ec=(a,b)=>{b=V(b);U(a,{name:b,fromWireType:function(c){for(var d=E[c>>2],e=c+4,f,g=e,h=0;h<=d;++h){var k=e+h;if(h==d||0==z[k])g=R(g,k-g),void 0===f?f=g:(f+=String.fromCharCode(0),f+=g),g=k+1}X(c);return f},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new W("Cannot pass non-string to std::string");var f=e?Uf(d):d.length;var g=jh(4+f+1),h=g+4;E[g>>2]=f;e?Vf(d,z,h,f+1):z.set(d,h);null!==
c&&c.push(X,g);return g},K:gh,readValueFromPointer:ah,J(c){X(c)}})};ec.g="vpp";
var ci=new TextDecoder("utf-16le"),di=(a,b)=>{a>>=1;b=a+b/2;for(var c=a;!(c>=b)&&C[c];)++c;return ci.decode(C.buffer instanceof ArrayBuffer?C.subarray(a,c):C.slice(a,c))},ei=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)A[b>>1]=a.charCodeAt(e),b+=2;A[b>>1]=0;return b-d},fi=a=>2*a.length,gi=(a,b)=>{for(var c="",d=0;!(d>=b/4);d++){var e=D[a+4*d>>2];if(!e)break;c+=String.fromCodePoint(e)}return c},hi=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=
b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;D[b>>2]=f;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},ii=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},fc=(a,b,c)=>{c=V(c);if(2===b){var d=di;var e=ei;var f=fi;var g=h=>C[h>>1]}else 4===b&&(d=gi,e=hi,f=ii,g=h=>E[h>>2]);U(a,{name:c,fromWireType:h=>{for(var k=E[h>>2],l,p=h+4,n=0;n<=k;++n){var q=h+4+n*b;if(n==k||0==g(q))p=d(p,q-p),void 0===l?l=p:(l+=String.fromCharCode(0),l+=p),p=q+b}X(h);return l},
toWireType:(h,k)=>{if("string"!=typeof k)throw new W(`Cannot pass non-string to C++ string type ${c}`);var l=f(k),p=jh(4+l+b);E[p>>2]=l/b;e(k,p+4,l+b);null!==h&&h.push(X,p);return p},K:gh,readValueFromPointer:ah,J(h){X(h)}})};fc.g="vppp";var gc=(a,b,c,d,e,f)=>{Zg[a]={name:V(b),Oa:Y(c,d),Y:Y(e,f),Za:[]}};gc.g="vpppppp";var hc=(a,b,c,d,e,f,g,h,k,l)=>{Zg[a].Za.push({Bb:V(b),Hb:c,la:Y(d,e),Gb:f,ic:g,hc:Y(h,k),jc:l})};hc.g="vpppppppppp";
var ic=(a,b)=>{b=V(b);U(a,{Sb:!0,name:b,K:0,fromWireType:()=>{},toWireType:()=>{}})};ic.g="vpp";var jc=(a,b,c,d)=>{function e(h){var k=R(a+36);Xg(`'Could not load dynamic lib: ${k}\n${h}`);--I;Xe(()=>P(c)(a,d))}function f(){--I;Xe(()=>P(b)(a,d))}I+=1;var g=Yg(a,{H:!0});g?g.then(f,e):e()};jc.g="vpppp";var kc=()=>{for(const a of Object.keys(Ae)){const b=Number(a);Be.has(b)||ji(b)}};kc.g="v";function ki(a){var b=li,c=b.O.pop()||b.ca.length;b.ca[c]=a;return c}
function mi(a){var b=li;b.ca[a]=void 0;b.O.push(a)}class ni{ca=[void 0];O=[];get(a){return this.ca[a]}has(a){return void 0!==this.ca[a]}}var li=new ni,oi=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=ki(a);return a},lc=(a,b,c)=>{const d=[];0===Object.keys(Ce).length||Za();var e=oi();d.push(e.promise);pi(e.id);for(const f of Object.keys(Ae)){const g=Number(f);g===a||Be.has(g)||(e=oi(),qi(g,e.id),Ce[g]=e,d.push(e.promise))}Promise.all(d).then(()=>{Ce={};P(b)(c)})};lc.g="vppp";
function mc(){var a=jh(4*(ma.length+1)),b=a;ma.forEach(c=>{var d=E,e=b>>2,f=Uf(c)+1,g=jh(f);g&&Vf(c,z,g,f);d[e]=g;b+=4});E[b>>2]=0;return a}mc.g="p";var nc=a=>{Da(a,!ba,1,!aa,262144,!1);Ea()};nc.g="vp";var Fa=a=>{"function"===typeof Atomics.qc&&(Atomics.qc(D,a>>2,a).value.then(Ia),Atomics.store(D,a+128>>2,1))};Fa.g="vp";var Ia=()=>{var a=Pe();a&&(Fa(a),Xe(ri))},oc=(a,b)=>{a==b?setTimeout(Ia):t?postMessage({Ca:a,U:"checkMailbox"}):(a=Ae[a])&&a.postMessage({U:"checkMailbox"})};oc.g="vpp";
var si=[],pc=(a,b,c,d,e)=>{d/=2;si.length=d;c=e>>3;for(e=0;e<d;e++)si[e]=F[c+2*e]?F[c+2*e+1]:La[c+2*e+1];return(b?Gf[b]:ti[a])(...si)};pc.g="dippip";var qc=()=>{Se=!1;I=0};qc.g="v";var rc=a=>{t?postMessage({U:"cleanupThread",Qa:a}):Ge(a)};rc.g="vp";var sc=a=>{t?postMessage({U:"markAsFinished",Qa:a}):(Be.add(a),a in Ce&&Ce[a].resolve())};sc.g="vp";var tc=()=>{};tc.g="vp";var uc=()=>{throw new ra;};uc.g="v";
var ui=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(E[b>>2]=Eh(d));return a},vc=(a,b,c)=>{a=Z(a);b=ai(b,"emval::as");return ui(b,c,a)};vc.g="dppp";var vi=[],wc=(a,b,c,d)=>{a=vi[a];b=Z(b);return a(null,b,c,d)};wc.g="dpppp";var wi={},xi=a=>{var b=wi[a];return void 0===b?V(a):b},yc=a=>{if(0===a)return Eh(globalThis);a=xi(a);return Eh(globalThis[a])};yc.g="pp";
var yi=a=>{var b=vi.length;vi.push(a);return b},zi=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=ai(E[b+4*d>>2],`parameter ${d}`);return c},zc=(a,b,c)=>{b=zi(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",f=0,g=[];0===c&&g.push("obj");for(var h=["retType"],k=[d],l=0;l<a;++l)g.push(`arg${l}`),h.push(`argType${l}`),k.push(b[l]),e+=`  var arg${l} = argType${l}.readValueFromPointer(args${f?"+"+f:""});\n`,f+=b[l].K;e+=`  var rv = ${1===c?"new func":"func.call"}(${g.join(", ")});\n`;
d.Sb||(h.push("emval_returnValue"),k.push(ui),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");a=(new Function(...h,e+"};\n"))(...k);c=`methodCaller<(${b.map(p=>p.name).join(", ")}) => ${d.name}>`;return yi(uh(c,a))};zc.g="pipi";var Ac=a=>{a=xi(a);return Eh(m[a])};Ac.g="pp";var Bc=(a,b)=>{a=Z(a);b=Z(b);return Eh(a[b])};Bc.g="ppp";var Cc=a=>{9<a&&(Yh[a+1]+=1)};Cc.g="vp";var Dc=(a,b)=>{a=Z(a);b=Z(b);return a instanceof b};Dc.g="ipp";var Ec=a=>{a=Z(a);return"number"==typeof a};Ec.g="ip";
var Fc=a=>{a=Z(a);return"string"==typeof a};Fc.g="ip";var Gc=a=>Eh(xi(a));Gc.g="pp";var Hc=a=>{var b=Z(a);$g(b);xc(a)};Hc.g="vp";var Ic=(a,b,c)=>{a=Z(a);b=Z(b);c=Z(c);a[b]=c};Ic.g="vppp";var Jc=(a,b)=>{a=ai(a,"_emval_take_value");a=a.readValueFromPointer(b);return Eh(a)};Jc.g="ppp";var Kc=a=>{a=Z(a);return Eh(typeof a)};Kc.g="pp";
function Lc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);D[b>>2]=a.getUTCSeconds();D[b+4>>2]=a.getUTCMinutes();D[b+8>>2]=a.getUTCHours();D[b+12>>2]=a.getUTCDate();D[b+16>>2]=a.getUTCMonth();D[b+20>>2]=a.getUTCFullYear()-1900;D[b+24>>2]=a.getUTCDay();D[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0}Lc.g="vjp";var Ai=[0,31,60,91,121,152,182,213,244,274,305,335],Bi=[0,31,59,90,120,151,181,212,243,273,304,334];
function Mc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);D[b>>2]=a.getSeconds();D[b+4>>2]=a.getMinutes();D[b+8>>2]=a.getHours();D[b+12>>2]=a.getDate();D[b+16>>2]=a.getMonth();D[b+20>>2]=a.getFullYear()-1900;D[b+24>>2]=a.getDay();var c=a.getFullYear();D[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Bi:Ai)[a.getMonth()]+a.getDate()-1|0;D[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
D[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}Mc.g="vjp";function Nc(a,b,c,d,e,f,g){if(t)return O(17,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var h=T(d),k=FS.ia(h,a,e,b,c),l=k.s;D[f>>2]=k.ca;E[g>>2]=l;return 0}catch(p){if("undefined"==typeof FS||"ErrnoError"!==p.name)throw p;return-p.A}}Nc.g="ipiiijpp";
function Oc(a,b,c,d,e,f){if(t)return O(18,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=T(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.h(43);d&2||FS.ka(g,z.slice(a,a+b),c,b,d)}}catch(h){if("undefined"==typeof FS||"ErrnoError"!==h.name)throw h;return-h.A}}Oc.g="ippiiij";
var Pc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();E[a>>2]=60*Math.max(f,e);D[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Vf(a,z,c,17),Vf(b,z,d,17)):(Vf(a,z,d,17),Vf(b,z,c,17))};Pc.g="vpppp";var Wc=()=>performance.timeOrigin+performance.now();Wc.g="d";var Sc=()=>Date.now();Sc.g="d";var Ci=1;
function Qc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(Ci)a=performance.timeOrigin+performance.now();else return 52;F[c>>3]=BigInt(Math.round(1E6*a));return 0}Qc.g="iijp";var Rc=()=>{};Rc.g="v";var Tc=a=>v(R(a));Tc.g="vp";var Uc=()=>{I+=1;throw"unwind";};Uc.g="v";var Vc=()=>z.length;Vc.g="p";var Xc=()=>navigator.hardwareConcurrency;Xc.g="i";var Yc=a=>{mi(a)};Yc.g="vp";
var Zc=(a,b,c)=>{a=li.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(li.get(c).promise);break;case 2:a.resolve(li.get(c).promise);mi(c);break;case 3:a.reject(c)}};Zc.g="vpip";var $c=()=>!1;$c.g="ip";
var Di={},Fi=()=>{if(!Ei){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Di)void 0===Di[b]?delete a[b]:a[b]=Di[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ei=c}return Ei},Ei;function ad(a,b){if(t)return O(19,1,a,b);var c=0,d=0,e;for(e of Fi()){var f=b+c;E[a+d>>2]=f;c+=Vf(e,z,f,Infinity)+1;d+=4}return 0}ad.g="ipp";
function bd(a,b){if(t)return O(20,1,a,b);var c=Fi();E[a>>2]=c.length;a=0;for(var d of c)a+=Uf(d)+1;E[b>>2]=a;return 0}bd.g="ipp";function dd(a){if(t)return O(21,1,a);try{var b=T(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.A}}dd.g="ii";
function ed(a,b){if(t)return O(22,1,a,b);try{var c=T(a),d=c.B?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;y[b]=d;A[b+2>>1]=0;F[b+8>>3]=BigInt(0);F[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.A}}ed.g="iip";
function fd(a,b,c,d){if(t)return O(23,1,a,b,c,d);try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var h=E[a>>2],k=E[a+4>>2];a+=8;var l=FS.read(e,y,h,k,f);if(0>l){var p=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}p=b}E[d>>2]=p;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return n.A}}fd.g="iippp";
function gd(a,b,c,d){if(t)return O(24,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=T(a);FS.llseek(e,b,c);F[d>>3]=BigInt(e.position);e.Ea&&0===b&&0===c&&(e.Ea=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.A}}gd.g="iijip";
function hd(a,b,c,d){if(t)return O(25,1,a,b,c,d);try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var h=E[a>>2],k=E[a+4>>2];a+=8;var l=FS.write(e,y,h,k,f);if(0>l){var p=-1;break a}b+=l;if(l<k)break;"undefined"!=typeof f&&(f+=l)}p=b}E[d>>2]=p;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return n.A}}hd.g="iippp";function kd(...a){return G.heif_color_conversion_options_ext_copy(...a)}kd.G=!0;function ld(...a){return G.heif_color_conversion_options_ext_free(...a)}ld.G=!0;
function md(...a){return G.heif_encoding_options_alloc(...a)}md.G=!0;function nd(...a){return G.heif_encoding_options_free(...a)}nd.G=!0;function od(...a){return G.heif_error_success(...a)}od.G=!0;function pd(...a){return G.heif_image_get_bits_per_pixel_range(...a)}pd.G=!0;function qd(...a){return G.heif_image_get_chroma_format(...a)}qd.G=!0;function rd(...a){return G.heif_image_get_nclx_color_profile(...a)}rd.G=!0;function sd(...a){return G.heif_image_get_plane_readonly2(...a)}sd.G=!0;
function td(...a){return G.heif_image_release(...a)}td.G=!0;function ud(...a){return G.heif_nclx_color_profile_free(...a)}ud.G=!0;function vd(...a){return G.heif_tai_clock_info_release(...a)}vd.G=!0;function wd(...a){return G.heif_tai_timestamp_packet_alloc(...a)}wd.G=!0;function xd(...a){return G.heif_tai_timestamp_packet_copy(...a)}xd.G=!0;function yd(...a){return G.heif_tai_timestamp_packet_release(...a)}yd.G=!0;
function ve(a,b){try{return Yf(z.subarray(a,a+b)),0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.A}}ve.g="ipp";var ta=a=>{var b=J(),c=Qe(4),d=Qe(4);Gi(a,c,d);a=E[c>>2];d=E[d>>2];c=R(a);X(a);if(d){var e=R(d);X(d)}K(b);return[c,e]};t||Me();
(()=>{var a={promiseChainEnd:Promise.resolve(),canHandle:b=>!m.noWasmDecoding&&b.endsWith(".so"),handle:(b,c,d,e)=>{a.promiseChainEnd=a.promiseChainEnd.then(()=>Kf(b,{H:!0,oa:!0},c,{})).then(f=>{$e[c]=f;d(b)},f=>{v(`failed to instantiate wasm: ${c}: ${f}`);e()})}};Ze.push(a)})();FS.createPreloadedFile=mg;FS.V=Array(4096);FS.mount(S,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));dg(FS.makedev(5,0),fg);dg(FS.makedev(6,0),gg);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Yf(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.o={llseek:S.o.llseek};b.m={ha(c,d){c=+d;var e=T(c);c={parent:null,mount:{fb:"fake"},m:{readlink:()=>e.path},id:c+1};return c.parent=c},ra(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.Cb={MEMFS:S};S.Wa=new FS.h(44);S.Wa.stack="<generic error, no stack>";
(()=>{let a=th.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof th&&c instanceof th))return!1;var d=this.l.C.v,e=this.l.s;c.l=c.l;var f=c.l.C.v;for(c=c.l.s;d.L;)e=d.ta(e),d=d.L;for(;f.L;)c=f.ta(c),f=f.L;return d===f&&e===c},clone:function(){this.l.s||lh(this);if(this.l.pa)return this.l.count.value+=1,this;var c=ph,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.l;c=c(e.call(d,f,{l:{value:{count:g.count,ga:g.ga,pa:g.pa,s:g.s,C:g.C,I:g.I,P:g.P}}}));c.l.count.value+=1;c.l.ga=
!1;return c},["delete"](){this.l.s||lh(this);if(this.l.ga&&!this.l.pa)throw new W("Object already scheduled for deletion");oh(this);var c=this.l;--c.count.value;0===c.count.value&&(c.I?c.P.Y(c.I):c.C.v.Y(c.s));this.l.pa||(this.l.I=void 0,this.l.s=void 0)},isDeleted:function(){return!this.l.s},deleteLater:function(){this.l.s||lh(this);if(this.l.ga&&!this.l.pa)throw new W("Object already scheduled for deletion");qh.push(this);1===qh.length&&sh&&sh(rh);this.l.ga=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(Kh.prototype,{Fb(a){this.hb&&(a=this.hb(a));return a},Ua(a){this.Y?.(a)},K:gh,readValueFromPointer:ah,fromWireType:function(a){function b(){return this.za?Jh(this.v.da,{C:this.bc,s:c,P:this,I:a}):Jh(this.v.da,{C:this,s:a})}var c=this.Fb(a);if(!c)return this.Ua(a),null;var d=Ih(this.v,c);if(void 0!==d){if(0===d.l.count.value)return d.l.s=c,d.l.I=a,d.clone();d=d.clone();this.Ua(a);return d}d=this.v.Db(c);d=vh[d];if(!d)return b.call(this);d=this.ya?d.wb:d.pointerType;var e=Gh(c,this.v,
d.v);return null===e?b.call(this):this.za?Jh(d.v.da,{C:d,s:e,P:this,I:a}):Jh(d.v.da,{C:d,s:e})}});He.push(()=>{Di.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;Di.VIPS_CONCURRENCY=1});
Ua.push(()=>{const a=Object.getOwnPropertyDescriptor(m.SourceCustom.prototype,"onRead");Object.defineProperty(m.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>Eh(c(d)))}});const b=Object.getOwnPropertyDescriptor(m.TargetCustom.prototype,"onWrite");Object.defineProperty(m.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Z(d)))}})});Object.assign(th.prototype,{preventAutoDelete:function(){const a=qh.indexOf(this);-1<a&&qh.splice(a,1);this.l.ga=!1;return this}});
if(!t){if(m.wasmMemory)za=m.wasmMemory;else{var Hi=m.INITIAL_MEMORY||1073741824;za=new WebAssembly.Memory({initial:Hi/65536,maximum:Hi/65536,shared:!0})}Ba()}m.preloadPlugins&&(Ze=m.preloadPlugins);m.noExitRuntime&&(Se=m.noExitRuntime);m.print&&(la=m.print);m.printErr&&(v=m.printErr);m.dynamicLibraries&&(ma=m.dynamicLibraries);m.wasmBinary&&(na=m.wasmBinary);m.arguments&&(ca=m.arguments);m.thisProgram&&(da=m.thisProgram);m.addRunDependency=Xa;m.removeRunDependency=Ya;m.ENV=Di;m.addFunction=zf;
m.FS_createPreloadedFile=mg;m.FS_unlink=(...a)=>FS.unlink(...a);m.FS_createPath=(...a)=>FS.createPath(...a);m.FS_createDevice=(...a)=>FS.createDevice(...a);m.FS=FS;m.FS_createDataFile=(...a)=>FS.createDataFile(...a);m.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);m.setAutoDeleteLater=a=>{mh=a};m.deletionQueue=qh;m.setDelayFunction=a=>{sh=a;qh.length&&sh&&sh(rh)};m.incrementExceptionRefcount=a=>Kg(a);m.decrementExceptionRefcount=a=>Ng(a);m.getExceptionMessage=a=>ta(a);
var ti=[ue,Te,Qg,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Nc,Oc,ad,bd,dd,ed,fd,gd,hd],Gf={};function Ii(a){for(var b=C[a+6>>1];13===b&&!(16<E[a>>2]);){var c=E[a+8>>2],d=E[c>>2];if(0===d){b=0;break}else if(0===E[(c>>2)+1])a=d,b=C[d+6>>1];else break}return[a,b]}
function jd(a,b,c,d){var e=E[(a>>2)+1],f=E[(a>>2)+6],g=E[(a>>2)+2];a=Ii(E[(a>>2)+3])[1];var h=J(),k=h,l=[],p=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)l.push(c),p=!0;for(var n=0;n<f;n++){var q=E[(d>>2)+n],r=Ii(E[(g>>2)+n]),u=r[0];r=r[1];switch(r){case 1:case 10:case 9:case 14:l.push(E[q>>2]);break;case 2:l.push(Ka[q>>2]);break;case 3:l.push(La[q>>3]);break;case 5:l.push(z[q]);break;case 6:l.push(y[q]);break;case 7:l.push(C[q>>
1]);break;case 8:l.push(A[q>>1]);break;case 11:case 12:l.push(Ma[q>>3]);break;case 4:l.push(Ma[q>>3]);l.push(Ma[(q>>3)+1]);break;case 13:r=E[u>>2];u=C[u+4>>1];k-=r;k&=~(u-1);y.subarray(k,k+r).set(y.subarray(q,q+r));l.push(k);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+r);}}if(f!=e){var x=[];for(n=e-1;n>=f;n--)switch(q=E[(d>>2)+n],r=Ii(E[(g>>2)+n]),u=r[0],r=r[1],r){case 5:case 6:--k;k&=-1;z[k]=z[q];break;case 7:case 8:k-=2;k&=-2;C[k>>1]=C[q>>1];break;
case 1:case 9:case 10:case 14:case 2:k-=4;k&=-4;E[k>>2]=E[q>>2];break;case 3:case 11:case 12:k-=8;k&=-8;E[k>>2]=E[q>>2];E[(k>>2)+1]=E[(q>>2)+1];break;case 4:k-=16;k&=-8;E[k>>2]=E[q>>2];E[(k>>2)+1]=E[(q>>2)+1];E[(k>>2)+2]=E[(q>>2)+2];E[(k>>2)+3]=E[(q>>2)+3];break;case 13:k-=4;k&=-4;x.push([k,q,E[u>>2],C[u+4>>1]]);break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+r);}l.push(k);for(n=0;n<x.length;n++)e=x[n],d=e[0],q=e[1],r=e[2],u=e[3],k-=r,k&=~(u-1),y.subarray(k,
k+r).set(y.subarray(q,q+r)),E[d>>2]=k}K(k);Qe(0);b=P(b).apply(null,l);K(h);if(!p)switch(a){case 0:break;case 1:case 9:case 10:case 14:E[c>>2]=b;break;case 2:Ka[c>>2]=b;break;case 3:La[c>>3]=b;break;case 5:case 6:z[c+0]=b;break;case 7:case 8:C[c>>1]=b;break;case 11:case 12:Ma[c>>3]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}jd.g="viiii";var Nh,Ga,Pe,jh,X,Ve,tf,hg,Ue,Wg,pi,of,qi,ji,Eg,Da,Ja,Re,Fe,We,ri,Q,Og,jf,K,Qe,J,Kg,Ng,Gi,Pg,Lg;
m.___THREW__=1204;m.__ZTISt12length_error=1441800;m.__ZTVSt12length_error=1441780;m.__ZTVN10__cxxabiv120__si_class_type_infoE=1441472;m.__ZTVN10__cxxabiv117__class_type_infoE=1441432;m.__ZTISt20bad_array_new_length=1441672;m.___threwValue=1208;m._stdout=1427328;m._stderr=1427176;m._g_mem_gc_friendly=3363004;m._g_utf8_skip=1370372;m.__ZTVNSt3__215basic_streambufIcNS_11char_traitsIcEEEE=1444896;m.__ZTVNSt3__215basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1445304;
m.__ZTTNSt3__218basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1445720;m.__ZTTNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1445952;m.__ZTVNSt3__218basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1445660;m.__ZTVNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE=1445912;m.__ZNSt3__24coutE=3413456;m.__ZNSt3__24cerrE=3413632;m.__ZNSt3__25ctypeIcE2idE=3410664;m.__ZTINSt3__219__shared_weak_countE=1441956;
m.__ZTVNSt3__212bad_weak_ptrE=1441980;m.__ZTINSt3__212bad_weak_ptrE=1442E3;m.__ZSt7nothrow=946532;m.__ZTISt12out_of_range=1441832;m.__ZTVSt12out_of_range=1441812;m.__ZTVN10__cxxabiv121__vmi_class_type_infoE=1441524;
var G,Ta=await (async function(){function a(c,d){Ta=c.exports;Ta=Af(Ta,1024);var e=mf(d);Lf(Ta);rf("__main__",0,G);Gg();If(Ta._emscripten_tls_init,c.exports,e);Qa.push(Ta.__wasm_apply_data_relocs);oa=d;c=Ta;Nh=c.__getTypeName;Ga=c._embind_initialize_bindings;Pe=c.pthread_self;jh=c.malloc;m._main=c.main;X=c.free;Ve=c.fflush;tf=c.calloc;m._emscripten_builtin_free=c.emscripten_builtin_free;hg=c.emscripten_builtin_memalign;m._emscripten_builtin_malloc=c.emscripten_builtin_malloc;Ue=c.__funcs_on_exit;
m.___libc_calloc=c.__libc_calloc;m.___libc_free=c.__libc_free;m.___libc_malloc=c.__libc_malloc;Wg=c.__dl_seterr;pi=c._emscripten_dlsync_self_async;of=c._emscripten_dlsync_self;qi=c._emscripten_proxy_dlsync_async;ji=c._emscripten_proxy_dlsync;Eg=c._emscripten_find_dylib;Da=c._emscripten_thread_init;Ja=c._emscripten_thread_crashed;Re=c._emscripten_run_on_main_thread_js;Fe=c._emscripten_thread_free_data;We=c._emscripten_thread_exit;m._strndup=c.strndup;ri=c._emscripten_check_mailbox;m.__ZdaPvm=c._ZdaPvm;
m.__Znaj=c._Znaj;m.__ZnajSt11align_val_t=c._ZnajSt11align_val_t;m.__Znwj=c._Znwj;m.__ZnwjSt11align_val_t=c._ZnwjSt11align_val_t;m.___libc_realloc=c.__libc_realloc;m._emscripten_builtin_calloc=c.emscripten_builtin_calloc;m._emscripten_builtin_realloc=c.emscripten_builtin_realloc;m._malloc_size=c.malloc_size;m._malloc_usable_size=c.malloc_usable_size;m._reallocf=c.reallocf;Q=c.setThrew;Og=c._emscripten_tempret_set;jf=c.emscripten_stack_set_limits;K=c._emscripten_stack_restore;Qe=c._emscripten_stack_alloc;
J=c.emscripten_stack_get_current;Kg=c.__cxa_increment_exception_refcount;Ng=c.__cxa_decrement_exception_refcount;Gi=c.__get_exception_message;Pg=c.__cxa_can_catch;Lg=c.__cxa_get_exception_ptr;Ya("wasm-instantiate");return Ta}Xa("wasm-instantiate");var b=db();if(m.instantiateWasm)return new Promise(c=>{m.instantiateWasm(b,(d,e)=>{c(a(d,e))})});if(t)return new Promise(c=>{wa=d=>{var e=new WebAssembly.Instance(d,db());c(a(e,d))}});$a??=ha("vips.wasm");return function(c){return a(c.instance,c.module)}(await cb(b))}());
function Vd(a,b){var c=J();try{P(a)(b)}catch(d){K(c);if(!(d instanceof w))throw d;Q(1,0)}}function ce(a,b,c,d){var e=J();try{P(a)(b,c,d)}catch(f){K(e);if(!(f instanceof w))throw f;Q(1,0)}}function Gd(a,b,c){var d=J();try{return P(a)(b,c)}catch(e){K(d);if(!(e instanceof w))throw e;Q(1,0)}}function Ud(a){var b=J();try{P(a)()}catch(c){K(b);if(!(c instanceof w))throw c;Q(1,0)}}function Fd(a,b){var c=J();try{return P(a)(b)}catch(d){K(c);if(!(d instanceof w))throw d;Q(1,0)}}
function Ed(a){var b=J();try{return P(a)()}catch(c){K(b);if(!(c instanceof w))throw c;Q(1,0)}}function je(a,b,c,d,e){var f=J();try{P(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof w))throw g;Q(1,0)}}function Bd(a,b,c,d){var e=J();try{return P(a)(b,c,d)}catch(f){K(e);if(!(f instanceof w))throw f;Q(1,0)}}function Yd(a,b,c){var d=J();try{P(a)(b,c)}catch(e){K(d);if(!(e instanceof w))throw e;Q(1,0)}}function Id(a,b,c,d){var e=J();try{return P(a)(b,c,d)}catch(f){K(e);if(!(f instanceof w))throw f;Q(1,0)}}
function Ld(a,b,c,d,e,f){var g=J();try{return P(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof w))throw h;Q(1,0)}}function ke(a,b,c,d,e,f){var g=J();try{P(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof w))throw h;Q(1,0)}}function Md(a,b,c,d,e,f,g){var h=J();try{return P(a)(b,c,d,e,f,g)}catch(k){K(h);if(!(k instanceof w))throw k;Q(1,0)}}function Jd(a,b,c,d,e){var f=J();try{return P(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof w))throw g;Q(1,0)}}
function Zd(a,b,c,d){var e=J();try{P(a)(b,c,d)}catch(f){K(e);if(!(f instanceof w))throw f;Q(1,0)}}function $d(a,b,c,d,e){var f=J();try{P(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof w))throw g;Q(1,0)}}function Hd(a,b,c,d){var e=J();try{return P(a)(b,c,d)}catch(f){K(e);if(!(f instanceof w))throw f;Q(1,0)}}function Wd(a,b,c){var d=J();try{P(a)(b,c)}catch(e){K(d);if(!(e instanceof w))throw e;Q(1,0)}}
function Cd(a,b,c,d,e){var f=J();try{return P(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof w))throw g;Q(1,0)}}function zd(a,b){var c=J();try{return P(a)(b)}catch(d){K(c);if(!(d instanceof w))throw d;Q(1,0)}}function pe(a,b,c,d,e,f,g,h,k,l,p){var n=J();try{P(a)(b,c,d,e,f,g,h,k,l,p)}catch(q){K(n);if(!(q instanceof w))throw q;Q(1,0)}}function le(a,b,c,d,e,f,g){var h=J();try{P(a)(b,c,d,e,f,g)}catch(k){K(h);if(!(k instanceof w))throw k;Q(1,0)}}
function me(a,b,c,d,e,f,g,h){var k=J();try{P(a)(b,c,d,e,f,g,h)}catch(l){K(k);if(!(l instanceof w))throw l;Q(1,0)}}function Ad(a,b,c){var d=J();try{return P(a)(b,c)}catch(e){K(d);if(!(e instanceof w))throw e;Q(1,0)}}function be(a,b,c,d,e){var f=J();try{P(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof w))throw g;Q(1,0)}}function de(a,b,c,d,e){var f=J();try{P(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof w))throw g;Q(1,0)}}
function Xd(a,b,c,d,e){var f=J();try{P(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof w))throw g;Q(1,0)}}function ge(a,b,c,d,e,f,g,h){var k=J();try{P(a)(b,c,d,e,f,g,h)}catch(l){K(k);if(!(l instanceof w))throw l;Q(1,0)}}function ee(a,b,c,d,e,f,g,h,k,l){var p=J();try{P(a)(b,c,d,e,f,g,h,k,l)}catch(n){K(p);if(!(n instanceof w))throw n;Q(1,0)}}function fe(a,b,c,d,e,f,g,h,k){var l=J();try{P(a)(b,c,d,e,f,g,h,k)}catch(p){K(l);if(!(p instanceof w))throw p;Q(1,0)}}
function ie(a,b,c,d,e,f){var g=J();try{P(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof w))throw h;Q(1,0)}}function he(a,b,c,d,e,f,g){var h=J();try{P(a)(b,c,d,e,f,g)}catch(k){K(h);if(!(k instanceof w))throw k;Q(1,0)}}function re(a,b,c,d,e,f,g,h,k,l,p,n,q){var r=J();try{P(a)(b,c,d,e,f,g,h,k,l,p,n,q)}catch(u){K(r);if(!(u instanceof w))throw u;Q(1,0)}}function qe(a,b,c,d,e,f,g,h,k,l,p,n){var q=J();try{P(a)(b,c,d,e,f,g,h,k,l,p,n)}catch(r){K(q);if(!(r instanceof w))throw r;Q(1,0)}}
function oe(a,b,c,d,e,f,g,h,k,l){var p=J();try{P(a)(b,c,d,e,f,g,h,k,l)}catch(n){K(p);if(!(n instanceof w))throw n;Q(1,0)}}function ne(a,b,c,d,e,f,g,h,k){var l=J();try{P(a)(b,c,d,e,f,g,h,k)}catch(p){K(l);if(!(p instanceof w))throw p;Q(1,0)}}function se(a,b,c,d,e,f,g,h,k,l,p,n,q,r){var u=J();try{P(a)(b,c,d,e,f,g,h,k,l,p,n,q,r)}catch(x){K(u);if(!(x instanceof w))throw x;Q(1,0)}}function ae(a,b,c,d,e,f){var g=J();try{P(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof w))throw h;Q(1,0)}}
function Nd(a,b,c,d,e,f,g,h){var k=J();try{return P(a)(b,c,d,e,f,g,h)}catch(l){K(k);if(!(l instanceof w))throw l;Q(1,0)}}function Sd(a,b){var c=J();try{return P(a)(b)}catch(d){K(c);if(!(d instanceof w))throw d;Q(1,0);return 0n}}function Qd(a,b,c,d,e,f,g,h,k,l,p,n,q){var r=J();try{return P(a)(b,c,d,e,f,g,h,k,l,p,n,q)}catch(u){K(r);if(!(u instanceof w))throw u;Q(1,0)}}function Td(a,b,c,d,e){var f=J();try{return P(a)(b,c,d,e)}catch(g){K(f);if(!(g instanceof w))throw g;Q(1,0);return 0n}}
function Dd(a,b,c,d){var e=J();try{return P(a)(b,c,d)}catch(f){K(e);if(!(f instanceof w))throw f;Q(1,0)}}function Od(a,b,c,d,e,f,g,h,k,l,p){var n=J();try{return P(a)(b,c,d,e,f,g,h,k,l,p)}catch(q){K(n);if(!(q instanceof w))throw q;Q(1,0)}}function Pd(a,b,c,d,e,f,g,h,k,l,p,n){var q=J();try{return P(a)(b,c,d,e,f,g,h,k,l,p,n)}catch(r){K(q);if(!(r instanceof w))throw r;Q(1,0)}}
function te(a,b,c,d,e,f,g,h,k,l,p,n,q,r,u,x){var B=J();try{P(a)(b,c,d,e,f,g,h,k,l,p,n,q,r,u,x)}catch(L){K(B);if(!(L instanceof w))throw L;Q(1,0)}}function Rd(a,b,c,d,e,f){var g=J();try{return P(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof w))throw h;Q(1,0)}}function Kd(a,b,c,d,e,f){var g=J();try{return P(a)(b,c,d,e,f)}catch(h){K(g);if(!(h instanceof w))throw h;Q(1,0)}}
function Ji(a=[]){var b=Ff("main").Pa;if(b){a.unshift(da);var c=a.length,d=Qe(4*(c+1)),e=d;a.forEach(g=>{E[e>>2]=Wf(g);e+=4});E[e>>2]=0;try{var f=b(c,d);cd(f,!0)}catch(g){ye(g)}}}
function Ki(a=ca){function b(){m.calledRun=!0;if(!pa&&(Ra(),ua?.(m),m.onRuntimeInitialized?.(),m.noInitialRun||Ji(a),!t)){if(m.postRun)for("function"==typeof m.postRun&&(m.postRun=[m.postRun]);m.postRun.length;){var c=m.postRun.shift();hf.push(c)}Sa(hf)}}if(0<Va)Wa=Ki;else if(t)ua?.(m),Ra();else{if(m.preRun)for("function"==typeof m.preRun&&(m.preRun=[m.preRun]);m.preRun.length;)He.push(m.preRun.shift());Sa(He);0<Va?Wa=Ki:m.setStatus?(m.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>m.setStatus(""),
1);b()},1)):b()}}if(m.preInit)for("function"==typeof m.preInit&&(m.preInit=[m.preInit]);0<m.preInit.length;)m.preInit.shift()();Ki();Oa?moduleRtn=m:moduleRtn=new Promise((a,b)=>{ua=a;va=b});


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = Vips;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = Vips;
} else if (typeof define === 'function' && define['amd'])
  define([], () => Vips);
var isPthread = globalThis.self?.name?.startsWith('em-pthread');
// When running as a pthread, construct a new instance on startup
isPthread && Vips();
